/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateWorkflowCommandForms type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkflowCommandForms{}

// CreateWorkflowCommandForms struct for CreateWorkflowCommandForms
type CreateWorkflowCommandForms struct {
	FormId int64 `json:"form/id"`
}

type _CreateWorkflowCommandForms CreateWorkflowCommandForms

// NewCreateWorkflowCommandForms instantiates a new CreateWorkflowCommandForms object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkflowCommandForms(formId int64) *CreateWorkflowCommandForms {
	this := CreateWorkflowCommandForms{}
	this.FormId = formId
	return &this
}

// NewCreateWorkflowCommandFormsWithDefaults instantiates a new CreateWorkflowCommandForms object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkflowCommandFormsWithDefaults() *CreateWorkflowCommandForms {
	this := CreateWorkflowCommandForms{}
	return &this
}

// GetFormId returns the FormId field value
func (o *CreateWorkflowCommandForms) GetFormId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FormId
}

// GetFormIdOk returns a tuple with the FormId field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowCommandForms) GetFormIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormId, true
}

// SetFormId sets field value
func (o *CreateWorkflowCommandForms) SetFormId(v int64) {
	o.FormId = v
}

func (o CreateWorkflowCommandForms) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkflowCommandForms) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["form/id"] = o.FormId
	return toSerialize, nil
}

func (o *CreateWorkflowCommandForms) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"form/id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkflowCommandForms := _CreateWorkflowCommandForms{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWorkflowCommandForms)

	if err != nil {
		return err
	}

	*o = CreateWorkflowCommandForms(varCreateWorkflowCommandForms)

	return err
}

type NullableCreateWorkflowCommandForms struct {
	value *CreateWorkflowCommandForms
	isSet bool
}

func (v NullableCreateWorkflowCommandForms) Get() *CreateWorkflowCommandForms {
	return v.value
}

func (v *NullableCreateWorkflowCommandForms) Set(val *CreateWorkflowCommandForms) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkflowCommandForms) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkflowCommandForms) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkflowCommandForms(val *CreateWorkflowCommandForms) *NullableCreateWorkflowCommandForms {
	return &NullableCreateWorkflowCommandForms{value: val, isSet: true}
}

func (v NullableCreateWorkflowCommandForms) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkflowCommandForms) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
