/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UninviteMemberCommandMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UninviteMemberCommandMember{}

// UninviteMemberCommandMember struct for UninviteMemberCommandMember
type UninviteMemberCommandMember struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type _UninviteMemberCommandMember UninviteMemberCommandMember

// NewUninviteMemberCommandMember instantiates a new UninviteMemberCommandMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUninviteMemberCommandMember(name string, email string) *UninviteMemberCommandMember {
	this := UninviteMemberCommandMember{}
	this.Name = name
	this.Email = email
	return &this
}

// NewUninviteMemberCommandMemberWithDefaults instantiates a new UninviteMemberCommandMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUninviteMemberCommandMemberWithDefaults() *UninviteMemberCommandMember {
	this := UninviteMemberCommandMember{}
	return &this
}

// GetName returns the Name field value
func (o *UninviteMemberCommandMember) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UninviteMemberCommandMember) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UninviteMemberCommandMember) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *UninviteMemberCommandMember) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UninviteMemberCommandMember) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UninviteMemberCommandMember) SetEmail(v string) {
	o.Email = v
}

func (o UninviteMemberCommandMember) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UninviteMemberCommandMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *UninviteMemberCommandMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUninviteMemberCommandMember := _UninviteMemberCommandMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUninviteMemberCommandMember)

	if err != nil {
		return err
	}

	*o = UninviteMemberCommandMember(varUninviteMemberCommandMember)

	return err
}

type NullableUninviteMemberCommandMember struct {
	value *UninviteMemberCommandMember
	isSet bool
}

func (v NullableUninviteMemberCommandMember) Get() *UninviteMemberCommandMember {
	return v.value
}

func (v *NullableUninviteMemberCommandMember) Set(val *UninviteMemberCommandMember) {
	v.value = val
	v.isSet = true
}

func (v NullableUninviteMemberCommandMember) IsSet() bool {
	return v.isSet
}

func (v *NullableUninviteMemberCommandMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUninviteMemberCommandMember(val *UninviteMemberCommandMember) *NullableUninviteMemberCommandMember {
	return &NullableUninviteMemberCommandMember{value: val, isSet: true}
}

func (v NullableUninviteMemberCommandMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUninviteMemberCommandMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
