/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response7960Resource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7960Resource{}

// Response7960Resource struct for Response7960Resource
type Response7960Resource struct {
	ResourceExtId string `json:"resource/ext-id"`
}

type _Response7960Resource Response7960Resource

// NewResponse7960Resource instantiates a new Response7960Resource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7960Resource(resourceExtId string) *Response7960Resource {
	this := Response7960Resource{}
	this.ResourceExtId = resourceExtId
	return &this
}

// NewResponse7960ResourceWithDefaults instantiates a new Response7960Resource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7960ResourceWithDefaults() *Response7960Resource {
	this := Response7960Resource{}
	return &this
}

// GetResourceExtId returns the ResourceExtId field value
func (o *Response7960Resource) GetResourceExtId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceExtId
}

// GetResourceExtIdOk returns a tuple with the ResourceExtId field value
// and a boolean to check if the value has been set.
func (o *Response7960Resource) GetResourceExtIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceExtId, true
}

// SetResourceExtId sets field value
func (o *Response7960Resource) SetResourceExtId(v string) {
	o.ResourceExtId = v
}

func (o Response7960Resource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7960Resource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource/ext-id"] = o.ResourceExtId
	return toSerialize, nil
}

func (o *Response7960Resource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource/ext-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse7960Resource := _Response7960Resource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse7960Resource)

	if err != nil {
		return err
	}

	*o = Response7960Resource(varResponse7960Resource)

	return err
}

type NullableResponse7960Resource struct {
	value *Response7960Resource
	isSet bool
}

func (v NullableResponse7960Resource) Get() *Response7960Resource {
	return v.value
}

func (v *NullableResponse7960Resource) Set(val *Response7960Resource) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7960Resource) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7960Resource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7960Resource(val *Response7960Resource) *NullableResponse7960Resource {
	return &NullableResponse7960Resource{value: val, isSet: true}
}

func (v NullableResponse7960Resource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7960Resource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
