/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response6556DuoCodesRestrictionsValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response6556DuoCodesRestrictionsValues{}

// Response6556DuoCodesRestrictionsValues struct for Response6556DuoCodesRestrictionsValues
type Response6556DuoCodesRestrictionsValues struct {
	Value string `json:"value"`
}

type _Response6556DuoCodesRestrictionsValues Response6556DuoCodesRestrictionsValues

// NewResponse6556DuoCodesRestrictionsValues instantiates a new Response6556DuoCodesRestrictionsValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse6556DuoCodesRestrictionsValues(value string) *Response6556DuoCodesRestrictionsValues {
	this := Response6556DuoCodesRestrictionsValues{}
	this.Value = value
	return &this
}

// NewResponse6556DuoCodesRestrictionsValuesWithDefaults instantiates a new Response6556DuoCodesRestrictionsValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse6556DuoCodesRestrictionsValuesWithDefaults() *Response6556DuoCodesRestrictionsValues {
	this := Response6556DuoCodesRestrictionsValues{}
	return &this
}

// GetValue returns the Value field value
func (o *Response6556DuoCodesRestrictionsValues) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Response6556DuoCodesRestrictionsValues) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Response6556DuoCodesRestrictionsValues) SetValue(v string) {
	o.Value = v
}

func (o Response6556DuoCodesRestrictionsValues) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response6556DuoCodesRestrictionsValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *Response6556DuoCodesRestrictionsValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse6556DuoCodesRestrictionsValues := _Response6556DuoCodesRestrictionsValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse6556DuoCodesRestrictionsValues)

	if err != nil {
		return err
	}

	*o = Response6556DuoCodesRestrictionsValues(varResponse6556DuoCodesRestrictionsValues)

	return err
}

type NullableResponse6556DuoCodesRestrictionsValues struct {
	value *Response6556DuoCodesRestrictionsValues
	isSet bool
}

func (v NullableResponse6556DuoCodesRestrictionsValues) Get() *Response6556DuoCodesRestrictionsValues {
	return v.value
}

func (v *NullableResponse6556DuoCodesRestrictionsValues) Set(val *Response6556DuoCodesRestrictionsValues) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse6556DuoCodesRestrictionsValues) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse6556DuoCodesRestrictionsValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse6556DuoCodesRestrictionsValues(val *Response6556DuoCodesRestrictionsValues) *NullableResponse6556DuoCodesRestrictionsValues {
	return &NullableResponse6556DuoCodesRestrictionsValues{value: val, isSet: true}
}

func (v NullableResponse6556DuoCodesRestrictionsValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse6556DuoCodesRestrictionsValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
