/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710{}

// GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 struct for GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710
type GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 struct {
	Id       int64          `json:"id"`
	Langcode string         `json:"langcode"`
	Title    string         `json:"title"`
	Infourl  NullableString `json:"infourl"`
}

type _GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710

// NewGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 instantiates a new GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710(id int64, langcode string, title string, infourl NullableString) *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 {
	this := GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710{}
	this.Id = id
	this.Langcode = langcode
	this.Title = title
	this.Infourl = infourl
	return &this
}

// NewGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710WithDefaults instantiates a new GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710WithDefaults() *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 {
	this := GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710{}
	return &this
}

// GetId returns the Id field value
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) SetId(v int64) {
	o.Id = v
}

// GetLangcode returns the Langcode field value
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) GetLangcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Langcode
}

// GetLangcodeOk returns a tuple with the Langcode field value
// and a boolean to check if the value has been set.
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) GetLangcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Langcode, true
}

// SetLangcode sets field value
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) SetLangcode(v string) {
	o.Langcode = v
}

// GetTitle returns the Title field value
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) SetTitle(v string) {
	o.Title = v
}

// GetInfourl returns the Infourl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) GetInfourl() string {
	if o == nil || o.Infourl.Get() == nil {
		var ret string
		return ret
	}

	return *o.Infourl.Get()
}

// GetInfourlOk returns a tuple with the Infourl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) GetInfourlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Infourl.Get(), o.Infourl.IsSet()
}

// SetInfourl sets field value
func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) SetInfourl(v string) {
	o.Infourl.Set(&v)
}

func (o GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["langcode"] = o.Langcode
	toSerialize["title"] = o.Title
	toSerialize["infourl"] = o.Infourl.Get()
	return toSerialize, nil
}

func (o *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"langcode",
		"title",
		"infourl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 := _GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710)

	if err != nil {
		return err
	}

	*o = GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710(varGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710)

	return err
}

type NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 struct {
	value *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710
	isSet bool
}

func (v NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) Get() *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 {
	return v.value
}

func (v *NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) Set(val *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710(val *GetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) *NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710 {
	return &NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710{value: val, isSet: true}
}

func (v NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalogueTreeResponseRootsItemsLocalizationsKeyword6710) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
