/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetCatalogueTreeResponseRootsLocalizationsKeyword6715 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCatalogueTreeResponseRootsLocalizationsKeyword6715{}

// GetCatalogueTreeResponseRootsLocalizationsKeyword6715 struct for GetCatalogueTreeResponseRootsLocalizationsKeyword6715
type GetCatalogueTreeResponseRootsLocalizationsKeyword6715 struct {
	Id       int64          `json:"id"`
	Langcode string         `json:"langcode"`
	Title    string         `json:"title"`
	Infourl  NullableString `json:"infourl"`
}

type _GetCatalogueTreeResponseRootsLocalizationsKeyword6715 GetCatalogueTreeResponseRootsLocalizationsKeyword6715

// NewGetCatalogueTreeResponseRootsLocalizationsKeyword6715 instantiates a new GetCatalogueTreeResponseRootsLocalizationsKeyword6715 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCatalogueTreeResponseRootsLocalizationsKeyword6715(id int64, langcode string, title string, infourl NullableString) *GetCatalogueTreeResponseRootsLocalizationsKeyword6715 {
	this := GetCatalogueTreeResponseRootsLocalizationsKeyword6715{}
	this.Id = id
	this.Langcode = langcode
	this.Title = title
	this.Infourl = infourl
	return &this
}

// NewGetCatalogueTreeResponseRootsLocalizationsKeyword6715WithDefaults instantiates a new GetCatalogueTreeResponseRootsLocalizationsKeyword6715 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCatalogueTreeResponseRootsLocalizationsKeyword6715WithDefaults() *GetCatalogueTreeResponseRootsLocalizationsKeyword6715 {
	this := GetCatalogueTreeResponseRootsLocalizationsKeyword6715{}
	return &this
}

// GetId returns the Id field value
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) SetId(v int64) {
	o.Id = v
}

// GetLangcode returns the Langcode field value
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) GetLangcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Langcode
}

// GetLangcodeOk returns a tuple with the Langcode field value
// and a boolean to check if the value has been set.
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) GetLangcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Langcode, true
}

// SetLangcode sets field value
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) SetLangcode(v string) {
	o.Langcode = v
}

// GetTitle returns the Title field value
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) SetTitle(v string) {
	o.Title = v
}

// GetInfourl returns the Infourl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) GetInfourl() string {
	if o == nil || o.Infourl.Get() == nil {
		var ret string
		return ret
	}

	return *o.Infourl.Get()
}

// GetInfourlOk returns a tuple with the Infourl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) GetInfourlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Infourl.Get(), o.Infourl.IsSet()
}

// SetInfourl sets field value
func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) SetInfourl(v string) {
	o.Infourl.Set(&v)
}

func (o GetCatalogueTreeResponseRootsLocalizationsKeyword6715) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCatalogueTreeResponseRootsLocalizationsKeyword6715) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["langcode"] = o.Langcode
	toSerialize["title"] = o.Title
	toSerialize["infourl"] = o.Infourl.Get()
	return toSerialize, nil
}

func (o *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"langcode",
		"title",
		"infourl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCatalogueTreeResponseRootsLocalizationsKeyword6715 := _GetCatalogueTreeResponseRootsLocalizationsKeyword6715{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCatalogueTreeResponseRootsLocalizationsKeyword6715)

	if err != nil {
		return err
	}

	*o = GetCatalogueTreeResponseRootsLocalizationsKeyword6715(varGetCatalogueTreeResponseRootsLocalizationsKeyword6715)

	return err
}

type NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715 struct {
	value *GetCatalogueTreeResponseRootsLocalizationsKeyword6715
	isSet bool
}

func (v NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715) Get() *GetCatalogueTreeResponseRootsLocalizationsKeyword6715 {
	return v.value
}

func (v *NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715) Set(val *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715(val *GetCatalogueTreeResponseRootsLocalizationsKeyword6715) *NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715 {
	return &NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715{value: val, isSet: true}
}

func (v NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalogueTreeResponseRootsLocalizationsKeyword6715) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
