/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateCatalogueItemCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCatalogueItemCommand{}

// CreateCatalogueItemCommand struct for CreateCatalogueItemCommand
type CreateCatalogueItemCommand struct {
	Form         NullableInt64  `json:"form,omitempty"`
	Resid        int64          `json:"resid"`
	Wfid         int64          `json:"wfid"`
	Organization OrganizationId `json:"organization"`
	// Localizations keyed by language
	Localizations map[string]CatalogueItemLocalization `json:"localizations"`
	Enabled       *bool                                `json:"enabled,omitempty"`
	Archived      *bool                                `json:"archived,omitempty"`
	Categories    []CategoryId                         `json:"categories,omitempty"`
}

type _CreateCatalogueItemCommand CreateCatalogueItemCommand

// NewCreateCatalogueItemCommand instantiates a new CreateCatalogueItemCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCatalogueItemCommand(resid int64, wfid int64, organization OrganizationId, localizations map[string]CatalogueItemLocalization) *CreateCatalogueItemCommand {
	this := CreateCatalogueItemCommand{}
	this.Resid = resid
	this.Wfid = wfid
	this.Organization = organization
	this.Localizations = localizations
	return &this
}

// NewCreateCatalogueItemCommandWithDefaults instantiates a new CreateCatalogueItemCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCatalogueItemCommandWithDefaults() *CreateCatalogueItemCommand {
	this := CreateCatalogueItemCommand{}
	return &this
}

// GetForm returns the Form field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCatalogueItemCommand) GetForm() int64 {
	if o == nil || IsNil(o.Form.Get()) {
		var ret int64
		return ret
	}
	return *o.Form.Get()
}

// GetFormOk returns a tuple with the Form field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCatalogueItemCommand) GetFormOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Form.Get(), o.Form.IsSet()
}

// HasForm returns a boolean if a field has been set.
func (o *CreateCatalogueItemCommand) HasForm() bool {
	if o != nil && o.Form.IsSet() {
		return true
	}

	return false
}

// SetForm gets a reference to the given NullableInt64 and assigns it to the Form field.
func (o *CreateCatalogueItemCommand) SetForm(v int64) {
	o.Form.Set(&v)
}

// SetFormNil sets the value for Form to be an explicit nil
func (o *CreateCatalogueItemCommand) SetFormNil() {
	o.Form.Set(nil)
}

// UnsetForm ensures that no value is present for Form, not even an explicit nil
func (o *CreateCatalogueItemCommand) UnsetForm() {
	o.Form.Unset()
}

// GetResid returns the Resid field value
func (o *CreateCatalogueItemCommand) GetResid() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Resid
}

// GetResidOk returns a tuple with the Resid field value
// and a boolean to check if the value has been set.
func (o *CreateCatalogueItemCommand) GetResidOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resid, true
}

// SetResid sets field value
func (o *CreateCatalogueItemCommand) SetResid(v int64) {
	o.Resid = v
}

// GetWfid returns the Wfid field value
func (o *CreateCatalogueItemCommand) GetWfid() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Wfid
}

// GetWfidOk returns a tuple with the Wfid field value
// and a boolean to check if the value has been set.
func (o *CreateCatalogueItemCommand) GetWfidOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Wfid, true
}

// SetWfid sets field value
func (o *CreateCatalogueItemCommand) SetWfid(v int64) {
	o.Wfid = v
}

// GetOrganization returns the Organization field value
func (o *CreateCatalogueItemCommand) GetOrganization() OrganizationId {
	if o == nil {
		var ret OrganizationId
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *CreateCatalogueItemCommand) GetOrganizationOk() (*OrganizationId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *CreateCatalogueItemCommand) SetOrganization(v OrganizationId) {
	o.Organization = v
}

// GetLocalizations returns the Localizations field value
func (o *CreateCatalogueItemCommand) GetLocalizations() map[string]CatalogueItemLocalization {
	if o == nil {
		var ret map[string]CatalogueItemLocalization
		return ret
	}

	return o.Localizations
}

// GetLocalizationsOk returns a tuple with the Localizations field value
// and a boolean to check if the value has been set.
func (o *CreateCatalogueItemCommand) GetLocalizationsOk() (*map[string]CatalogueItemLocalization, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Localizations, true
}

// SetLocalizations sets field value
func (o *CreateCatalogueItemCommand) SetLocalizations(v map[string]CatalogueItemLocalization) {
	o.Localizations = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateCatalogueItemCommand) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCatalogueItemCommand) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateCatalogueItemCommand) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateCatalogueItemCommand) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *CreateCatalogueItemCommand) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCatalogueItemCommand) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *CreateCatalogueItemCommand) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *CreateCatalogueItemCommand) SetArchived(v bool) {
	o.Archived = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *CreateCatalogueItemCommand) GetCategories() []CategoryId {
	if o == nil || IsNil(o.Categories) {
		var ret []CategoryId
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCatalogueItemCommand) GetCategoriesOk() ([]CategoryId, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *CreateCatalogueItemCommand) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []CategoryId and assigns it to the Categories field.
func (o *CreateCatalogueItemCommand) SetCategories(v []CategoryId) {
	o.Categories = v
}

func (o CreateCatalogueItemCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCatalogueItemCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Form.IsSet() {
		toSerialize["form"] = o.Form.Get()
	}
	toSerialize["resid"] = o.Resid
	toSerialize["wfid"] = o.Wfid
	toSerialize["organization"] = o.Organization
	toSerialize["localizations"] = o.Localizations
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	return toSerialize, nil
}

func (o *CreateCatalogueItemCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resid",
		"wfid",
		"organization",
		"localizations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCatalogueItemCommand := _CreateCatalogueItemCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCatalogueItemCommand)

	if err != nil {
		return err
	}

	*o = CreateCatalogueItemCommand(varCreateCatalogueItemCommand)

	return err
}

type NullableCreateCatalogueItemCommand struct {
	value *CreateCatalogueItemCommand
	isSet bool
}

func (v NullableCreateCatalogueItemCommand) Get() *CreateCatalogueItemCommand {
	return v.value
}

func (v *NullableCreateCatalogueItemCommand) Set(val *CreateCatalogueItemCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCatalogueItemCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCatalogueItemCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCatalogueItemCommand(val *CreateCatalogueItemCommand) *NullableCreateCatalogueItemCommand {
	return &NullableCreateCatalogueItemCommand{value: val, isSet: true}
}

func (v NullableCreateCatalogueItemCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCatalogueItemCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
