/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response7799DuoCodesRestrictionsValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7799DuoCodesRestrictionsValues{}

// Response7799DuoCodesRestrictionsValues struct for Response7799DuoCodesRestrictionsValues
type Response7799DuoCodesRestrictionsValues struct {
	Value string `json:"value"`
}

type _Response7799DuoCodesRestrictionsValues Response7799DuoCodesRestrictionsValues

// NewResponse7799DuoCodesRestrictionsValues instantiates a new Response7799DuoCodesRestrictionsValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7799DuoCodesRestrictionsValues(value string) *Response7799DuoCodesRestrictionsValues {
	this := Response7799DuoCodesRestrictionsValues{}
	this.Value = value
	return &this
}

// NewResponse7799DuoCodesRestrictionsValuesWithDefaults instantiates a new Response7799DuoCodesRestrictionsValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7799DuoCodesRestrictionsValuesWithDefaults() *Response7799DuoCodesRestrictionsValues {
	this := Response7799DuoCodesRestrictionsValues{}
	return &this
}

// GetValue returns the Value field value
func (o *Response7799DuoCodesRestrictionsValues) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Response7799DuoCodesRestrictionsValues) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Response7799DuoCodesRestrictionsValues) SetValue(v string) {
	o.Value = v
}

func (o Response7799DuoCodesRestrictionsValues) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7799DuoCodesRestrictionsValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *Response7799DuoCodesRestrictionsValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse7799DuoCodesRestrictionsValues := _Response7799DuoCodesRestrictionsValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse7799DuoCodesRestrictionsValues)

	if err != nil {
		return err
	}

	*o = Response7799DuoCodesRestrictionsValues(varResponse7799DuoCodesRestrictionsValues)

	return err
}

type NullableResponse7799DuoCodesRestrictionsValues struct {
	value *Response7799DuoCodesRestrictionsValues
	isSet bool
}

func (v NullableResponse7799DuoCodesRestrictionsValues) Get() *Response7799DuoCodesRestrictionsValues {
	return v.value
}

func (v *NullableResponse7799DuoCodesRestrictionsValues) Set(val *Response7799DuoCodesRestrictionsValues) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7799DuoCodesRestrictionsValues) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7799DuoCodesRestrictionsValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7799DuoCodesRestrictionsValues(val *Response7799DuoCodesRestrictionsValues) *NullableResponse7799DuoCodesRestrictionsValues {
	return &NullableResponse7799DuoCodesRestrictionsValues{value: val, isSet: true}
}

func (v NullableResponse7799DuoCodesRestrictionsValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7799DuoCodesRestrictionsValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
