/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
)

// checks if the Response6556ProcessingState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response6556ProcessingState{}

// Response6556ProcessingState struct for Response6556ProcessingState
type Response6556ProcessingState struct {
	Public  *ProcessingState `json:"public,omitempty"`
	Private *ProcessingState `json:"private,omitempty"`
}

// NewResponse6556ProcessingState instantiates a new Response6556ProcessingState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse6556ProcessingState() *Response6556ProcessingState {
	this := Response6556ProcessingState{}
	return &this
}

// NewResponse6556ProcessingStateWithDefaults instantiates a new Response6556ProcessingState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse6556ProcessingStateWithDefaults() *Response6556ProcessingState {
	this := Response6556ProcessingState{}
	return &this
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *Response6556ProcessingState) GetPublic() ProcessingState {
	if o == nil || IsNil(o.Public) {
		var ret ProcessingState
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response6556ProcessingState) GetPublicOk() (*ProcessingState, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *Response6556ProcessingState) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given ProcessingState and assigns it to the Public field.
func (o *Response6556ProcessingState) SetPublic(v ProcessingState) {
	o.Public = &v
}

// GetPrivate returns the Private field value if set, zero value otherwise.
func (o *Response6556ProcessingState) GetPrivate() ProcessingState {
	if o == nil || IsNil(o.Private) {
		var ret ProcessingState
		return ret
	}
	return *o.Private
}

// GetPrivateOk returns a tuple with the Private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response6556ProcessingState) GetPrivateOk() (*ProcessingState, bool) {
	if o == nil || IsNil(o.Private) {
		return nil, false
	}
	return o.Private, true
}

// HasPrivate returns a boolean if a field has been set.
func (o *Response6556ProcessingState) HasPrivate() bool {
	if o != nil && !IsNil(o.Private) {
		return true
	}

	return false
}

// SetPrivate gets a reference to the given ProcessingState and assigns it to the Private field.
func (o *Response6556ProcessingState) SetPrivate(v ProcessingState) {
	o.Private = &v
}

func (o Response6556ProcessingState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response6556ProcessingState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	if !IsNil(o.Private) {
		toSerialize["private"] = o.Private
	}
	return toSerialize, nil
}

type NullableResponse6556ProcessingState struct {
	value *Response6556ProcessingState
	isSet bool
}

func (v NullableResponse6556ProcessingState) Get() *Response6556ProcessingState {
	return v.value
}

func (v *NullableResponse6556ProcessingState) Set(val *Response6556ProcessingState) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse6556ProcessingState) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse6556ProcessingState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse6556ProcessingState(val *Response6556ProcessingState) *NullableResponse6556ProcessingState {
	return &NullableResponse6556ProcessingState{value: val, isSet: true}
}

func (v NullableResponse6556ProcessingState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse6556ProcessingState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
