/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AddLicensesCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddLicensesCommand{}

// AddLicensesCommand struct for AddLicensesCommand
type AddLicensesCommand struct {
	ApplicationId int64               `json:"application-id"`
	Comment       *string             `json:"comment,omitempty"`
	Attachments   []CommandAttachment `json:"attachments,omitempty"`
	Licenses      []int64             `json:"licenses"`
}

type _AddLicensesCommand AddLicensesCommand

// NewAddLicensesCommand instantiates a new AddLicensesCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddLicensesCommand(applicationId int64, licenses []int64) *AddLicensesCommand {
	this := AddLicensesCommand{}
	this.ApplicationId = applicationId
	this.Licenses = licenses
	return &this
}

// NewAddLicensesCommandWithDefaults instantiates a new AddLicensesCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddLicensesCommandWithDefaults() *AddLicensesCommand {
	this := AddLicensesCommand{}
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *AddLicensesCommand) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *AddLicensesCommand) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *AddLicensesCommand) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *AddLicensesCommand) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddLicensesCommand) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *AddLicensesCommand) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *AddLicensesCommand) SetComment(v string) {
	o.Comment = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *AddLicensesCommand) GetAttachments() []CommandAttachment {
	if o == nil || IsNil(o.Attachments) {
		var ret []CommandAttachment
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddLicensesCommand) GetAttachmentsOk() ([]CommandAttachment, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *AddLicensesCommand) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []CommandAttachment and assigns it to the Attachments field.
func (o *AddLicensesCommand) SetAttachments(v []CommandAttachment) {
	o.Attachments = v
}

// GetLicenses returns the Licenses field value
func (o *AddLicensesCommand) GetLicenses() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value
// and a boolean to check if the value has been set.
func (o *AddLicensesCommand) GetLicensesOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Licenses, true
}

// SetLicenses sets field value
func (o *AddLicensesCommand) SetLicenses(v []int64) {
	o.Licenses = v
}

func (o AddLicensesCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddLicensesCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["application-id"] = o.ApplicationId
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	toSerialize["licenses"] = o.Licenses
	return toSerialize, nil
}

func (o *AddLicensesCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"application-id",
		"licenses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddLicensesCommand := _AddLicensesCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddLicensesCommand)

	if err != nil {
		return err
	}

	*o = AddLicensesCommand(varAddLicensesCommand)

	return err
}

type NullableAddLicensesCommand struct {
	value *AddLicensesCommand
	isSet bool
}

func (v NullableAddLicensesCommand) Get() *AddLicensesCommand {
	return v.value
}

func (v *NullableAddLicensesCommand) Set(val *AddLicensesCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableAddLicensesCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableAddLicensesCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddLicensesCommand(val *AddLicensesCommand) *NullableAddLicensesCommand {
	return &NullableAddLicensesCommand{value: val, isSet: true}
}

func (v NullableAddLicensesCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddLicensesCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
