/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the Decider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Decider{}

// Decider struct for Decider
type Decider struct {
	Userid               string           `json:"userid"`
	Name                 NullableString   `json:"name"`
	Email                NullableString   `json:"email"`
	Organizations        []OrganizationId `json:"organizations,omitempty"`
	NotificationEmail    NullableString   `json:"notification-email,omitempty"`
	ResearcherStatusBy   *string          `json:"researcher-status-by,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Decider Decider

// NewDecider instantiates a new Decider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecider(userid string, name NullableString, email NullableString) *Decider {
	this := Decider{}
	this.Userid = userid
	this.Name = name
	this.Email = email
	return &this
}

// NewDeciderWithDefaults instantiates a new Decider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeciderWithDefaults() *Decider {
	this := Decider{}
	return &this
}

// GetUserid returns the Userid field value
func (o *Decider) GetUserid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Userid
}

// GetUseridOk returns a tuple with the Userid field value
// and a boolean to check if the value has been set.
func (o *Decider) GetUseridOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Userid, true
}

// SetUserid sets field value
func (o *Decider) SetUserid(v string) {
	o.Userid = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Decider) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Decider) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *Decider) SetName(v string) {
	o.Name.Set(&v)
}

// GetEmail returns the Email field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Decider) GetEmail() string {
	if o == nil || o.Email.Get() == nil {
		var ret string
		return ret
	}

	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Decider) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// SetEmail sets field value
func (o *Decider) SetEmail(v string) {
	o.Email.Set(&v)
}

// GetOrganizations returns the Organizations field value if set, zero value otherwise.
func (o *Decider) GetOrganizations() []OrganizationId {
	if o == nil || IsNil(o.Organizations) {
		var ret []OrganizationId
		return ret
	}
	return o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Decider) GetOrganizationsOk() ([]OrganizationId, bool) {
	if o == nil || IsNil(o.Organizations) {
		return nil, false
	}
	return o.Organizations, true
}

// HasOrganizations returns a boolean if a field has been set.
func (o *Decider) HasOrganizations() bool {
	if o != nil && !IsNil(o.Organizations) {
		return true
	}

	return false
}

// SetOrganizations gets a reference to the given []OrganizationId and assigns it to the Organizations field.
func (o *Decider) SetOrganizations(v []OrganizationId) {
	o.Organizations = v
}

// GetNotificationEmail returns the NotificationEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Decider) GetNotificationEmail() string {
	if o == nil || IsNil(o.NotificationEmail.Get()) {
		var ret string
		return ret
	}
	return *o.NotificationEmail.Get()
}

// GetNotificationEmailOk returns a tuple with the NotificationEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Decider) GetNotificationEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NotificationEmail.Get(), o.NotificationEmail.IsSet()
}

// HasNotificationEmail returns a boolean if a field has been set.
func (o *Decider) HasNotificationEmail() bool {
	if o != nil && o.NotificationEmail.IsSet() {
		return true
	}

	return false
}

// SetNotificationEmail gets a reference to the given NullableString and assigns it to the NotificationEmail field.
func (o *Decider) SetNotificationEmail(v string) {
	o.NotificationEmail.Set(&v)
}

// SetNotificationEmailNil sets the value for NotificationEmail to be an explicit nil
func (o *Decider) SetNotificationEmailNil() {
	o.NotificationEmail.Set(nil)
}

// UnsetNotificationEmail ensures that no value is present for NotificationEmail, not even an explicit nil
func (o *Decider) UnsetNotificationEmail() {
	o.NotificationEmail.Unset()
}

// GetResearcherStatusBy returns the ResearcherStatusBy field value if set, zero value otherwise.
func (o *Decider) GetResearcherStatusBy() string {
	if o == nil || IsNil(o.ResearcherStatusBy) {
		var ret string
		return ret
	}
	return *o.ResearcherStatusBy
}

// GetResearcherStatusByOk returns a tuple with the ResearcherStatusBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Decider) GetResearcherStatusByOk() (*string, bool) {
	if o == nil || IsNil(o.ResearcherStatusBy) {
		return nil, false
	}
	return o.ResearcherStatusBy, true
}

// HasResearcherStatusBy returns a boolean if a field has been set.
func (o *Decider) HasResearcherStatusBy() bool {
	if o != nil && !IsNil(o.ResearcherStatusBy) {
		return true
	}

	return false
}

// SetResearcherStatusBy gets a reference to the given string and assigns it to the ResearcherStatusBy field.
func (o *Decider) SetResearcherStatusBy(v string) {
	o.ResearcherStatusBy = &v
}

func (o Decider) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Decider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userid"] = o.Userid
	toSerialize["name"] = o.Name.Get()
	toSerialize["email"] = o.Email.Get()
	if !IsNil(o.Organizations) {
		toSerialize["organizations"] = o.Organizations
	}
	if o.NotificationEmail.IsSet() {
		toSerialize["notification-email"] = o.NotificationEmail.Get()
	}
	if !IsNil(o.ResearcherStatusBy) {
		toSerialize["researcher-status-by"] = o.ResearcherStatusBy
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Decider) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userid",
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDecider := _Decider{}

	err = json.Unmarshal(data, &varDecider)

	if err != nil {
		return err
	}

	*o = Decider(varDecider)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "userid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "email")
		delete(additionalProperties, "organizations")
		delete(additionalProperties, "notification-email")
		delete(additionalProperties, "researcher-status-by")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDecider struct {
	value *Decider
	isSet bool
}

func (v NullableDecider) Get() *Decider {
	return v.value
}

func (v *NullableDecider) Set(val *Decider) {
	v.value = val
	v.isSet = true
}

func (v NullableDecider) IsSet() bool {
	return v.isSet
}

func (v *NullableDecider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecider(val *Decider) *NullableDecider {
	return &NullableDecider{value: val, isSet: true}
}

func (v NullableDecider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
