/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response7862DuoCodesRestrictions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7862DuoCodesRestrictions{}

// Response7862DuoCodesRestrictions struct for Response7862DuoCodesRestrictions
type Response7862DuoCodesRestrictions struct {
	Type   string                   `json:"type"`
	Values []map[string]interface{} `json:"values,omitempty"`
}

type _Response7862DuoCodesRestrictions Response7862DuoCodesRestrictions

// NewResponse7862DuoCodesRestrictions instantiates a new Response7862DuoCodesRestrictions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7862DuoCodesRestrictions(type_ string) *Response7862DuoCodesRestrictions {
	this := Response7862DuoCodesRestrictions{}
	this.Type = type_
	return &this
}

// NewResponse7862DuoCodesRestrictionsWithDefaults instantiates a new Response7862DuoCodesRestrictions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7862DuoCodesRestrictionsWithDefaults() *Response7862DuoCodesRestrictions {
	this := Response7862DuoCodesRestrictions{}
	return &this
}

// GetType returns the Type field value
func (o *Response7862DuoCodesRestrictions) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Response7862DuoCodesRestrictions) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Response7862DuoCodesRestrictions) SetType(v string) {
	o.Type = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *Response7862DuoCodesRestrictions) GetValues() []map[string]interface{} {
	if o == nil || IsNil(o.Values) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response7862DuoCodesRestrictions) GetValuesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *Response7862DuoCodesRestrictions) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []map[string]interface{} and assigns it to the Values field.
func (o *Response7862DuoCodesRestrictions) SetValues(v []map[string]interface{}) {
	o.Values = v
}

func (o Response7862DuoCodesRestrictions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7862DuoCodesRestrictions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

func (o *Response7862DuoCodesRestrictions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse7862DuoCodesRestrictions := _Response7862DuoCodesRestrictions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse7862DuoCodesRestrictions)

	if err != nil {
		return err
	}

	*o = Response7862DuoCodesRestrictions(varResponse7862DuoCodesRestrictions)

	return err
}

type NullableResponse7862DuoCodesRestrictions struct {
	value *Response7862DuoCodesRestrictions
	isSet bool
}

func (v NullableResponse7862DuoCodesRestrictions) Get() *Response7862DuoCodesRestrictions {
	return v.value
}

func (v *NullableResponse7862DuoCodesRestrictions) Set(val *Response7862DuoCodesRestrictions) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7862DuoCodesRestrictions) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7862DuoCodesRestrictions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7862DuoCodesRestrictions(val *Response7862DuoCodesRestrictions) *NullableResponse7862DuoCodesRestrictions {
	return &NullableResponse7862DuoCodesRestrictions{value: val, isSet: true}
}

func (v NullableResponse7862DuoCodesRestrictions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7862DuoCodesRestrictions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
