/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateResourceCommandDuoCodesRestrictions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateResourceCommandDuoCodesRestrictions{}

// CreateResourceCommandDuoCodesRestrictions struct for CreateResourceCommandDuoCodesRestrictions
type CreateResourceCommandDuoCodesRestrictions struct {
	Type   string                   `json:"type"`
	Values []map[string]interface{} `json:"values,omitempty"`
}

type _CreateResourceCommandDuoCodesRestrictions CreateResourceCommandDuoCodesRestrictions

// NewCreateResourceCommandDuoCodesRestrictions instantiates a new CreateResourceCommandDuoCodesRestrictions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateResourceCommandDuoCodesRestrictions(type_ string) *CreateResourceCommandDuoCodesRestrictions {
	this := CreateResourceCommandDuoCodesRestrictions{}
	this.Type = type_
	return &this
}

// NewCreateResourceCommandDuoCodesRestrictionsWithDefaults instantiates a new CreateResourceCommandDuoCodesRestrictions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateResourceCommandDuoCodesRestrictionsWithDefaults() *CreateResourceCommandDuoCodesRestrictions {
	this := CreateResourceCommandDuoCodesRestrictions{}
	return &this
}

// GetType returns the Type field value
func (o *CreateResourceCommandDuoCodesRestrictions) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateResourceCommandDuoCodesRestrictions) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateResourceCommandDuoCodesRestrictions) SetType(v string) {
	o.Type = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *CreateResourceCommandDuoCodesRestrictions) GetValues() []map[string]interface{} {
	if o == nil || IsNil(o.Values) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateResourceCommandDuoCodesRestrictions) GetValuesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *CreateResourceCommandDuoCodesRestrictions) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []map[string]interface{} and assigns it to the Values field.
func (o *CreateResourceCommandDuoCodesRestrictions) SetValues(v []map[string]interface{}) {
	o.Values = v
}

func (o CreateResourceCommandDuoCodesRestrictions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateResourceCommandDuoCodesRestrictions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

func (o *CreateResourceCommandDuoCodesRestrictions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateResourceCommandDuoCodesRestrictions := _CreateResourceCommandDuoCodesRestrictions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateResourceCommandDuoCodesRestrictions)

	if err != nil {
		return err
	}

	*o = CreateResourceCommandDuoCodesRestrictions(varCreateResourceCommandDuoCodesRestrictions)

	return err
}

type NullableCreateResourceCommandDuoCodesRestrictions struct {
	value *CreateResourceCommandDuoCodesRestrictions
	isSet bool
}

func (v NullableCreateResourceCommandDuoCodesRestrictions) Get() *CreateResourceCommandDuoCodesRestrictions {
	return v.value
}

func (v *NullableCreateResourceCommandDuoCodesRestrictions) Set(val *CreateResourceCommandDuoCodesRestrictions) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateResourceCommandDuoCodesRestrictions) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateResourceCommandDuoCodesRestrictions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateResourceCommandDuoCodesRestrictions(val *CreateResourceCommandDuoCodesRestrictions) *NullableCreateResourceCommandDuoCodesRestrictions {
	return &NullableCreateResourceCommandDuoCodesRestrictions{value: val, isSet: true}
}

func (v NullableCreateResourceCommandDuoCodesRestrictions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateResourceCommandDuoCodesRestrictions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
