/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response6577DuoMatchesValidation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response6577DuoMatchesValidation{}

// Response6577DuoMatchesValidation struct for Response6577DuoMatchesValidation
type Response6577DuoMatchesValidation struct {
	Validity string                                   `json:"validity"`
	Errors   []Response6577DuoMatchesValidationErrors `json:"errors,omitempty"`
}

type _Response6577DuoMatchesValidation Response6577DuoMatchesValidation

// NewResponse6577DuoMatchesValidation instantiates a new Response6577DuoMatchesValidation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse6577DuoMatchesValidation(validity string) *Response6577DuoMatchesValidation {
	this := Response6577DuoMatchesValidation{}
	this.Validity = validity
	return &this
}

// NewResponse6577DuoMatchesValidationWithDefaults instantiates a new Response6577DuoMatchesValidation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse6577DuoMatchesValidationWithDefaults() *Response6577DuoMatchesValidation {
	this := Response6577DuoMatchesValidation{}
	return &this
}

// GetValidity returns the Validity field value
func (o *Response6577DuoMatchesValidation) GetValidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Validity
}

// GetValidityOk returns a tuple with the Validity field value
// and a boolean to check if the value has been set.
func (o *Response6577DuoMatchesValidation) GetValidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Validity, true
}

// SetValidity sets field value
func (o *Response6577DuoMatchesValidation) SetValidity(v string) {
	o.Validity = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *Response6577DuoMatchesValidation) GetErrors() []Response6577DuoMatchesValidationErrors {
	if o == nil || IsNil(o.Errors) {
		var ret []Response6577DuoMatchesValidationErrors
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response6577DuoMatchesValidation) GetErrorsOk() ([]Response6577DuoMatchesValidationErrors, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *Response6577DuoMatchesValidation) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Response6577DuoMatchesValidationErrors and assigns it to the Errors field.
func (o *Response6577DuoMatchesValidation) SetErrors(v []Response6577DuoMatchesValidationErrors) {
	o.Errors = v
}

func (o Response6577DuoMatchesValidation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response6577DuoMatchesValidation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["validity"] = o.Validity
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *Response6577DuoMatchesValidation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"validity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse6577DuoMatchesValidation := _Response6577DuoMatchesValidation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse6577DuoMatchesValidation)

	if err != nil {
		return err
	}

	*o = Response6577DuoMatchesValidation(varResponse6577DuoMatchesValidation)

	return err
}

type NullableResponse6577DuoMatchesValidation struct {
	value *Response6577DuoMatchesValidation
	isSet bool
}

func (v NullableResponse6577DuoMatchesValidation) Get() *Response6577DuoMatchesValidation {
	return v.value
}

func (v *NullableResponse6577DuoMatchesValidation) Set(val *Response6577DuoMatchesValidation) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse6577DuoMatchesValidation) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse6577DuoMatchesValidation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse6577DuoMatchesValidation(val *Response6577DuoMatchesValidation) *NullableResponse6577DuoMatchesValidation {
	return &NullableResponse6577DuoMatchesValidation{value: val, isSet: true}
}

func (v NullableResponse6577DuoMatchesValidation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse6577DuoMatchesValidation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
