/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response7799BlacklistResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7799BlacklistResource{}

// Response7799BlacklistResource struct for Response7799BlacklistResource
type Response7799BlacklistResource struct {
	ResourceExtId string `json:"resource/ext-id"`
}

type _Response7799BlacklistResource Response7799BlacklistResource

// NewResponse7799BlacklistResource instantiates a new Response7799BlacklistResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7799BlacklistResource(resourceExtId string) *Response7799BlacklistResource {
	this := Response7799BlacklistResource{}
	this.ResourceExtId = resourceExtId
	return &this
}

// NewResponse7799BlacklistResourceWithDefaults instantiates a new Response7799BlacklistResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7799BlacklistResourceWithDefaults() *Response7799BlacklistResource {
	this := Response7799BlacklistResource{}
	return &this
}

// GetResourceExtId returns the ResourceExtId field value
func (o *Response7799BlacklistResource) GetResourceExtId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceExtId
}

// GetResourceExtIdOk returns a tuple with the ResourceExtId field value
// and a boolean to check if the value has been set.
func (o *Response7799BlacklistResource) GetResourceExtIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceExtId, true
}

// SetResourceExtId sets field value
func (o *Response7799BlacklistResource) SetResourceExtId(v string) {
	o.ResourceExtId = v
}

func (o Response7799BlacklistResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7799BlacklistResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource/ext-id"] = o.ResourceExtId
	return toSerialize, nil
}

func (o *Response7799BlacklistResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource/ext-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse7799BlacklistResource := _Response7799BlacklistResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse7799BlacklistResource)

	if err != nil {
		return err
	}

	*o = Response7799BlacklistResource(varResponse7799BlacklistResource)

	return err
}

type NullableResponse7799BlacklistResource struct {
	value *Response7799BlacklistResource
	isSet bool
}

func (v NullableResponse7799BlacklistResource) Get() *Response7799BlacklistResource {
	return v.value
}

func (v *NullableResponse7799BlacklistResource) Set(val *Response7799BlacklistResource) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7799BlacklistResource) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7799BlacklistResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7799BlacklistResource(val *Response7799BlacklistResource) *NullableResponse7799BlacklistResource {
	return &NullableResponse7799BlacklistResource{value: val, isSet: true}
}

func (v NullableResponse7799BlacklistResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7799BlacklistResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
