/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VoteCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoteCommand{}

// VoteCommand struct for VoteCommand
type VoteCommand struct {
	ApplicationId int64               `json:"application-id"`
	Comment       *string             `json:"comment,omitempty"`
	Attachments   []CommandAttachment `json:"attachments,omitempty"`
	Vote          string              `json:"vote"`
}

type _VoteCommand VoteCommand

// NewVoteCommand instantiates a new VoteCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoteCommand(applicationId int64, vote string) *VoteCommand {
	this := VoteCommand{}
	this.ApplicationId = applicationId
	this.Vote = vote
	return &this
}

// NewVoteCommandWithDefaults instantiates a new VoteCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoteCommandWithDefaults() *VoteCommand {
	this := VoteCommand{}
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *VoteCommand) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *VoteCommand) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *VoteCommand) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *VoteCommand) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoteCommand) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *VoteCommand) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *VoteCommand) SetComment(v string) {
	o.Comment = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *VoteCommand) GetAttachments() []CommandAttachment {
	if o == nil || IsNil(o.Attachments) {
		var ret []CommandAttachment
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoteCommand) GetAttachmentsOk() ([]CommandAttachment, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *VoteCommand) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []CommandAttachment and assigns it to the Attachments field.
func (o *VoteCommand) SetAttachments(v []CommandAttachment) {
	o.Attachments = v
}

// GetVote returns the Vote field value
func (o *VoteCommand) GetVote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vote
}

// GetVoteOk returns a tuple with the Vote field value
// and a boolean to check if the value has been set.
func (o *VoteCommand) GetVoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vote, true
}

// SetVote sets field value
func (o *VoteCommand) SetVote(v string) {
	o.Vote = v
}

func (o VoteCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoteCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["application-id"] = o.ApplicationId
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	toSerialize["vote"] = o.Vote
	return toSerialize, nil
}

func (o *VoteCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"application-id",
		"vote",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoteCommand := _VoteCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVoteCommand)

	if err != nil {
		return err
	}

	*o = VoteCommand(varVoteCommand)

	return err
}

type NullableVoteCommand struct {
	value *VoteCommand
	isSet bool
}

func (v NullableVoteCommand) Get() *VoteCommand {
	return v.value
}

func (v *NullableVoteCommand) Set(val *VoteCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableVoteCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableVoteCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoteCommand(val *VoteCommand) *NullableVoteCommand {
	return &NullableVoteCommand{value: val, isSet: true}
}

func (v NullableVoteCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoteCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
