/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InviteMemberCommandMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteMemberCommandMember{}

// InviteMemberCommandMember struct for InviteMemberCommandMember
type InviteMemberCommandMember struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type _InviteMemberCommandMember InviteMemberCommandMember

// NewInviteMemberCommandMember instantiates a new InviteMemberCommandMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteMemberCommandMember(name string, email string) *InviteMemberCommandMember {
	this := InviteMemberCommandMember{}
	this.Name = name
	this.Email = email
	return &this
}

// NewInviteMemberCommandMemberWithDefaults instantiates a new InviteMemberCommandMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteMemberCommandMemberWithDefaults() *InviteMemberCommandMember {
	this := InviteMemberCommandMember{}
	return &this
}

// GetName returns the Name field value
func (o *InviteMemberCommandMember) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InviteMemberCommandMember) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InviteMemberCommandMember) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *InviteMemberCommandMember) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InviteMemberCommandMember) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InviteMemberCommandMember) SetEmail(v string) {
	o.Email = v
}

func (o InviteMemberCommandMember) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteMemberCommandMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *InviteMemberCommandMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteMemberCommandMember := _InviteMemberCommandMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteMemberCommandMember)

	if err != nil {
		return err
	}

	*o = InviteMemberCommandMember(varInviteMemberCommandMember)

	return err
}

type NullableInviteMemberCommandMember struct {
	value *InviteMemberCommandMember
	isSet bool
}

func (v NullableInviteMemberCommandMember) Get() *InviteMemberCommandMember {
	return v.value
}

func (v *NullableInviteMemberCommandMember) Set(val *InviteMemberCommandMember) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteMemberCommandMember) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteMemberCommandMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteMemberCommandMember(val *InviteMemberCommandMember) *NullableInviteMemberCommandMember {
	return &NullableInviteMemberCommandMember{value: val, isSet: true}
}

func (v NullableInviteMemberCommandMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteMemberCommandMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
