/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
)

// checks if the ApplicationProcessingState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationProcessingState{}

// ApplicationProcessingState struct for ApplicationProcessingState
type ApplicationProcessingState struct {
	Public  *ProcessingState `json:"public,omitempty"`
	Private *ProcessingState `json:"private,omitempty"`
}

// NewApplicationProcessingState instantiates a new ApplicationProcessingState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationProcessingState() *ApplicationProcessingState {
	this := ApplicationProcessingState{}
	return &this
}

// NewApplicationProcessingStateWithDefaults instantiates a new ApplicationProcessingState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationProcessingStateWithDefaults() *ApplicationProcessingState {
	this := ApplicationProcessingState{}
	return &this
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *ApplicationProcessingState) GetPublic() ProcessingState {
	if o == nil || IsNil(o.Public) {
		var ret ProcessingState
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationProcessingState) GetPublicOk() (*ProcessingState, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *ApplicationProcessingState) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given ProcessingState and assigns it to the Public field.
func (o *ApplicationProcessingState) SetPublic(v ProcessingState) {
	o.Public = &v
}

// GetPrivate returns the Private field value if set, zero value otherwise.
func (o *ApplicationProcessingState) GetPrivate() ProcessingState {
	if o == nil || IsNil(o.Private) {
		var ret ProcessingState
		return ret
	}
	return *o.Private
}

// GetPrivateOk returns a tuple with the Private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationProcessingState) GetPrivateOk() (*ProcessingState, bool) {
	if o == nil || IsNil(o.Private) {
		return nil, false
	}
	return o.Private, true
}

// HasPrivate returns a boolean if a field has been set.
func (o *ApplicationProcessingState) HasPrivate() bool {
	if o != nil && !IsNil(o.Private) {
		return true
	}

	return false
}

// SetPrivate gets a reference to the given ProcessingState and assigns it to the Private field.
func (o *ApplicationProcessingState) SetPrivate(v ProcessingState) {
	o.Private = &v
}

func (o ApplicationProcessingState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationProcessingState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	if !IsNil(o.Private) {
		toSerialize["private"] = o.Private
	}
	return toSerialize, nil
}

type NullableApplicationProcessingState struct {
	value *ApplicationProcessingState
	isSet bool
}

func (v NullableApplicationProcessingState) Get() *ApplicationProcessingState {
	return v.value
}

func (v *NullableApplicationProcessingState) Set(val *ApplicationProcessingState) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationProcessingState) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationProcessingState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationProcessingState(val *ApplicationProcessingState) *NullableApplicationProcessingState {
	return &NullableApplicationProcessingState{value: val, isSet: true}
}

func (v NullableApplicationProcessingState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationProcessingState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
