/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
	"fmt"
)

// checks if the Response6556DuoMatchesValidationErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response6556DuoMatchesValidationErrors{}

// Response6556DuoMatchesValidationErrors struct for Response6556DuoMatchesValidationErrors
type Response6556DuoMatchesValidationErrors struct {
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _Response6556DuoMatchesValidationErrors Response6556DuoMatchesValidationErrors

// NewResponse6556DuoMatchesValidationErrors instantiates a new Response6556DuoMatchesValidationErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse6556DuoMatchesValidationErrors(type_ string) *Response6556DuoMatchesValidationErrors {
	this := Response6556DuoMatchesValidationErrors{}
	this.Type = type_
	return &this
}

// NewResponse6556DuoMatchesValidationErrorsWithDefaults instantiates a new Response6556DuoMatchesValidationErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse6556DuoMatchesValidationErrorsWithDefaults() *Response6556DuoMatchesValidationErrors {
	this := Response6556DuoMatchesValidationErrors{}
	return &this
}

// GetType returns the Type field value
func (o *Response6556DuoMatchesValidationErrors) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Response6556DuoMatchesValidationErrors) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Response6556DuoMatchesValidationErrors) SetType(v string) {
	o.Type = v
}

func (o Response6556DuoMatchesValidationErrors) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response6556DuoMatchesValidationErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Response6556DuoMatchesValidationErrors) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse6556DuoMatchesValidationErrors := _Response6556DuoMatchesValidationErrors{}

	err = json.Unmarshal(data, &varResponse6556DuoMatchesValidationErrors)

	if err != nil {
		return err
	}

	*o = Response6556DuoMatchesValidationErrors(varResponse6556DuoMatchesValidationErrors)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResponse6556DuoMatchesValidationErrors struct {
	value *Response6556DuoMatchesValidationErrors
	isSet bool
}

func (v NullableResponse6556DuoMatchesValidationErrors) Get() *Response6556DuoMatchesValidationErrors {
	return v.value
}

func (v *NullableResponse6556DuoMatchesValidationErrors) Set(val *Response6556DuoMatchesValidationErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse6556DuoMatchesValidationErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse6556DuoMatchesValidationErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse6556DuoMatchesValidationErrors(val *Response6556DuoMatchesValidationErrors) *NullableResponse6556DuoMatchesValidationErrors {
	return &NullableResponse6556DuoMatchesValidationErrors{value: val, isSet: true}
}

func (v NullableResponse6556DuoMatchesValidationErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse6556DuoMatchesValidationErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
