/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AddLicenseAttachmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddLicenseAttachmentResponse{}

// AddLicenseAttachmentResponse struct for AddLicenseAttachmentResponse
type AddLicenseAttachmentResponse struct {
	Success bool  `json:"success"`
	Id      int64 `json:"id"`
}

type _AddLicenseAttachmentResponse AddLicenseAttachmentResponse

// NewAddLicenseAttachmentResponse instantiates a new AddLicenseAttachmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddLicenseAttachmentResponse(success bool, id int64) *AddLicenseAttachmentResponse {
	this := AddLicenseAttachmentResponse{}
	this.Success = success
	this.Id = id
	return &this
}

// NewAddLicenseAttachmentResponseWithDefaults instantiates a new AddLicenseAttachmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddLicenseAttachmentResponseWithDefaults() *AddLicenseAttachmentResponse {
	this := AddLicenseAttachmentResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *AddLicenseAttachmentResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *AddLicenseAttachmentResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *AddLicenseAttachmentResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetId returns the Id field value
func (o *AddLicenseAttachmentResponse) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AddLicenseAttachmentResponse) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AddLicenseAttachmentResponse) SetId(v int64) {
	o.Id = v
}

func (o AddLicenseAttachmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddLicenseAttachmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *AddLicenseAttachmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddLicenseAttachmentResponse := _AddLicenseAttachmentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddLicenseAttachmentResponse)

	if err != nil {
		return err
	}

	*o = AddLicenseAttachmentResponse(varAddLicenseAttachmentResponse)

	return err
}

type NullableAddLicenseAttachmentResponse struct {
	value *AddLicenseAttachmentResponse
	isSet bool
}

func (v NullableAddLicenseAttachmentResponse) Get() *AddLicenseAttachmentResponse {
	return v.value
}

func (v *NullableAddLicenseAttachmentResponse) Set(val *AddLicenseAttachmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddLicenseAttachmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddLicenseAttachmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddLicenseAttachmentResponse(val *AddLicenseAttachmentResponse) *NullableAddLicenseAttachmentResponse {
	return &NullableAddLicenseAttachmentResponse{value: val, isSet: true}
}

func (v NullableAddLicenseAttachmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddLicenseAttachmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
