/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response6786RestrictionsValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response6786RestrictionsValues{}

// Response6786RestrictionsValues struct for Response6786RestrictionsValues
type Response6786RestrictionsValues struct {
	Value string `json:"value"`
}

type _Response6786RestrictionsValues Response6786RestrictionsValues

// NewResponse6786RestrictionsValues instantiates a new Response6786RestrictionsValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse6786RestrictionsValues(value string) *Response6786RestrictionsValues {
	this := Response6786RestrictionsValues{}
	this.Value = value
	return &this
}

// NewResponse6786RestrictionsValuesWithDefaults instantiates a new Response6786RestrictionsValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse6786RestrictionsValuesWithDefaults() *Response6786RestrictionsValues {
	this := Response6786RestrictionsValues{}
	return &this
}

// GetValue returns the Value field value
func (o *Response6786RestrictionsValues) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Response6786RestrictionsValues) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Response6786RestrictionsValues) SetValue(v string) {
	o.Value = v
}

func (o Response6786RestrictionsValues) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response6786RestrictionsValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *Response6786RestrictionsValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse6786RestrictionsValues := _Response6786RestrictionsValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse6786RestrictionsValues)

	if err != nil {
		return err
	}

	*o = Response6786RestrictionsValues(varResponse6786RestrictionsValues)

	return err
}

type NullableResponse6786RestrictionsValues struct {
	value *Response6786RestrictionsValues
	isSet bool
}

func (v NullableResponse6786RestrictionsValues) Get() *Response6786RestrictionsValues {
	return v.value
}

func (v *NullableResponse6786RestrictionsValues) Set(val *Response6786RestrictionsValues) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse6786RestrictionsValues) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse6786RestrictionsValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse6786RestrictionsValues(val *Response6786RestrictionsValues) *NullableResponse6786RestrictionsValues {
	return &NullableResponse6786RestrictionsValues{value: val, isSet: true}
}

func (v NullableResponse6786RestrictionsValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse6786RestrictionsValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
