/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationDuoMatchesValidation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationDuoMatchesValidation{}

// ApplicationDuoMatchesValidation struct for ApplicationDuoMatchesValidation
type ApplicationDuoMatchesValidation struct {
	Validity string                                  `json:"validity"`
	Errors   []ApplicationDuoMatchesValidationErrors `json:"errors,omitempty"`
}

type _ApplicationDuoMatchesValidation ApplicationDuoMatchesValidation

// NewApplicationDuoMatchesValidation instantiates a new ApplicationDuoMatchesValidation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationDuoMatchesValidation(validity string) *ApplicationDuoMatchesValidation {
	this := ApplicationDuoMatchesValidation{}
	this.Validity = validity
	return &this
}

// NewApplicationDuoMatchesValidationWithDefaults instantiates a new ApplicationDuoMatchesValidation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationDuoMatchesValidationWithDefaults() *ApplicationDuoMatchesValidation {
	this := ApplicationDuoMatchesValidation{}
	return &this
}

// GetValidity returns the Validity field value
func (o *ApplicationDuoMatchesValidation) GetValidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Validity
}

// GetValidityOk returns a tuple with the Validity field value
// and a boolean to check if the value has been set.
func (o *ApplicationDuoMatchesValidation) GetValidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Validity, true
}

// SetValidity sets field value
func (o *ApplicationDuoMatchesValidation) SetValidity(v string) {
	o.Validity = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ApplicationDuoMatchesValidation) GetErrors() []ApplicationDuoMatchesValidationErrors {
	if o == nil || IsNil(o.Errors) {
		var ret []ApplicationDuoMatchesValidationErrors
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationDuoMatchesValidation) GetErrorsOk() ([]ApplicationDuoMatchesValidationErrors, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ApplicationDuoMatchesValidation) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ApplicationDuoMatchesValidationErrors and assigns it to the Errors field.
func (o *ApplicationDuoMatchesValidation) SetErrors(v []ApplicationDuoMatchesValidationErrors) {
	o.Errors = v
}

func (o ApplicationDuoMatchesValidation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationDuoMatchesValidation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["validity"] = o.Validity
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *ApplicationDuoMatchesValidation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"validity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationDuoMatchesValidation := _ApplicationDuoMatchesValidation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationDuoMatchesValidation)

	if err != nil {
		return err
	}

	*o = ApplicationDuoMatchesValidation(varApplicationDuoMatchesValidation)

	return err
}

type NullableApplicationDuoMatchesValidation struct {
	value *ApplicationDuoMatchesValidation
	isSet bool
}

func (v NullableApplicationDuoMatchesValidation) Get() *ApplicationDuoMatchesValidation {
	return v.value
}

func (v *NullableApplicationDuoMatchesValidation) Set(val *ApplicationDuoMatchesValidation) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationDuoMatchesValidation) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationDuoMatchesValidation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationDuoMatchesValidation(val *ApplicationDuoMatchesValidation) *NullableApplicationDuoMatchesValidation {
	return &NullableApplicationDuoMatchesValidation{value: val, isSet: true}
}

func (v NullableApplicationDuoMatchesValidation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationDuoMatchesValidation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
