/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ResourceLicense type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceLicense{}

// ResourceLicense struct for ResourceLicense
type ResourceLicense struct {
	Id            int64                                                `json:"id"`
	Licensetype   string                                               `json:"licensetype"`
	Organization  OrganizationOverview                                 `json:"organization"`
	Enabled       bool                                                 `json:"enabled"`
	Archived      bool                                                 `json:"archived"`
	Localizations map[string]ResourcesLicensesLocalizationsKeyword8046 `json:"localizations"`
}

type _ResourceLicense ResourceLicense

// NewResourceLicense instantiates a new ResourceLicense object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceLicense(id int64, licensetype string, organization OrganizationOverview, enabled bool, archived bool, localizations map[string]ResourcesLicensesLocalizationsKeyword8046) *ResourceLicense {
	this := ResourceLicense{}
	this.Id = id
	this.Licensetype = licensetype
	this.Organization = organization
	this.Enabled = enabled
	this.Archived = archived
	this.Localizations = localizations
	return &this
}

// NewResourceLicenseWithDefaults instantiates a new ResourceLicense object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceLicenseWithDefaults() *ResourceLicense {
	this := ResourceLicense{}
	return &this
}

// GetId returns the Id field value
func (o *ResourceLicense) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResourceLicense) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResourceLicense) SetId(v int64) {
	o.Id = v
}

// GetLicensetype returns the Licensetype field value
func (o *ResourceLicense) GetLicensetype() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Licensetype
}

// GetLicensetypeOk returns a tuple with the Licensetype field value
// and a boolean to check if the value has been set.
func (o *ResourceLicense) GetLicensetypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Licensetype, true
}

// SetLicensetype sets field value
func (o *ResourceLicense) SetLicensetype(v string) {
	o.Licensetype = v
}

// GetOrganization returns the Organization field value
func (o *ResourceLicense) GetOrganization() OrganizationOverview {
	if o == nil {
		var ret OrganizationOverview
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *ResourceLicense) GetOrganizationOk() (*OrganizationOverview, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *ResourceLicense) SetOrganization(v OrganizationOverview) {
	o.Organization = v
}

// GetEnabled returns the Enabled field value
func (o *ResourceLicense) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ResourceLicense) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ResourceLicense) SetEnabled(v bool) {
	o.Enabled = v
}

// GetArchived returns the Archived field value
func (o *ResourceLicense) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *ResourceLicense) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *ResourceLicense) SetArchived(v bool) {
	o.Archived = v
}

// GetLocalizations returns the Localizations field value
func (o *ResourceLicense) GetLocalizations() map[string]ResourcesLicensesLocalizationsKeyword8046 {
	if o == nil {
		var ret map[string]ResourcesLicensesLocalizationsKeyword8046
		return ret
	}

	return o.Localizations
}

// GetLocalizationsOk returns a tuple with the Localizations field value
// and a boolean to check if the value has been set.
func (o *ResourceLicense) GetLocalizationsOk() (*map[string]ResourcesLicensesLocalizationsKeyword8046, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Localizations, true
}

// SetLocalizations sets field value
func (o *ResourceLicense) SetLocalizations(v map[string]ResourcesLicensesLocalizationsKeyword8046) {
	o.Localizations = v
}

func (o ResourceLicense) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceLicense) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["licensetype"] = o.Licensetype
	toSerialize["organization"] = o.Organization
	toSerialize["enabled"] = o.Enabled
	toSerialize["archived"] = o.Archived
	toSerialize["localizations"] = o.Localizations
	return toSerialize, nil
}

func (o *ResourceLicense) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"licensetype",
		"organization",
		"enabled",
		"archived",
		"localizations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceLicense := _ResourceLicense{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourceLicense)

	if err != nil {
		return err
	}

	*o = ResourceLicense(varResourceLicense)

	return err
}

type NullableResourceLicense struct {
	value *ResourceLicense
	isSet bool
}

func (v NullableResourceLicense) Get() *ResourceLicense {
	return v.value
}

func (v *NullableResourceLicense) Set(val *ResourceLicense) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceLicense) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceLicense) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceLicense(val *ResourceLicense) *NullableResourceLicense {
	return &NullableResourceLicense{value: val, isSet: true}
}

func (v NullableResourceLicense) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceLicense) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
