/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ChangeFormCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeFormCommand{}

// ChangeFormCommand struct for ChangeFormCommand
type ChangeFormCommand struct {
	// new form id
	Form NullableInt64 `json:"form"`
}

type _ChangeFormCommand ChangeFormCommand

// NewChangeFormCommand instantiates a new ChangeFormCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeFormCommand(form NullableInt64) *ChangeFormCommand {
	this := ChangeFormCommand{}
	this.Form = form
	return &this
}

// NewChangeFormCommandWithDefaults instantiates a new ChangeFormCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeFormCommandWithDefaults() *ChangeFormCommand {
	this := ChangeFormCommand{}
	return &this
}

// GetForm returns the Form field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *ChangeFormCommand) GetForm() int64 {
	if o == nil || o.Form.Get() == nil {
		var ret int64
		return ret
	}

	return *o.Form.Get()
}

// GetFormOk returns a tuple with the Form field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChangeFormCommand) GetFormOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Form.Get(), o.Form.IsSet()
}

// SetForm sets field value
func (o *ChangeFormCommand) SetForm(v int64) {
	o.Form.Set(&v)
}

func (o ChangeFormCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeFormCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["form"] = o.Form.Get()
	return toSerialize, nil
}

func (o *ChangeFormCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"form",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeFormCommand := _ChangeFormCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangeFormCommand)

	if err != nil {
		return err
	}

	*o = ChangeFormCommand(varChangeFormCommand)

	return err
}

type NullableChangeFormCommand struct {
	value *ChangeFormCommand
	isSet bool
}

func (v NullableChangeFormCommand) Get() *ChangeFormCommand {
	return v.value
}

func (v *NullableChangeFormCommand) Set(val *ChangeFormCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeFormCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeFormCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeFormCommand(val *ChangeFormCommand) *NullableChangeFormCommand {
	return &NullableChangeFormCommand{value: val, isSet: true}
}

func (v NullableChangeFormCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeFormCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
