/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateInvitationCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInvitationCommand{}

// CreateInvitationCommand struct for CreateInvitationCommand
type CreateInvitationCommand struct {
	Name       string `json:"name"`
	Email      string `json:"email"`
	WorkflowId *int64 `json:"workflow-id,omitempty"`
}

type _CreateInvitationCommand CreateInvitationCommand

// NewCreateInvitationCommand instantiates a new CreateInvitationCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInvitationCommand(name string, email string) *CreateInvitationCommand {
	this := CreateInvitationCommand{}
	this.Name = name
	this.Email = email
	return &this
}

// NewCreateInvitationCommandWithDefaults instantiates a new CreateInvitationCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInvitationCommandWithDefaults() *CreateInvitationCommand {
	this := CreateInvitationCommand{}
	return &this
}

// GetName returns the Name field value
func (o *CreateInvitationCommand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateInvitationCommand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateInvitationCommand) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *CreateInvitationCommand) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CreateInvitationCommand) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CreateInvitationCommand) SetEmail(v string) {
	o.Email = v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *CreateInvitationCommand) GetWorkflowId() int64 {
	if o == nil || IsNil(o.WorkflowId) {
		var ret int64
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInvitationCommand) GetWorkflowIdOk() (*int64, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *CreateInvitationCommand) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given int64 and assigns it to the WorkflowId field.
func (o *CreateInvitationCommand) SetWorkflowId(v int64) {
	o.WorkflowId = &v
}

func (o CreateInvitationCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInvitationCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow-id"] = o.WorkflowId
	}
	return toSerialize, nil
}

func (o *CreateInvitationCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInvitationCommand := _CreateInvitationCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateInvitationCommand)

	if err != nil {
		return err
	}

	*o = CreateInvitationCommand(varCreateInvitationCommand)

	return err
}

type NullableCreateInvitationCommand struct {
	value *CreateInvitationCommand
	isSet bool
}

func (v NullableCreateInvitationCommand) Get() *CreateInvitationCommand {
	return v.value
}

func (v *NullableCreateInvitationCommand) Set(val *CreateInvitationCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInvitationCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInvitationCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInvitationCommand(val *CreateInvitationCommand) *NullableCreateInvitationCommand {
	return &NullableCreateInvitationCommand{value: val, isSet: true}
}

func (v NullableCreateInvitationCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInvitationCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
