/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InviteReviewerCommandReviewer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteReviewerCommandReviewer{}

// InviteReviewerCommandReviewer struct for InviteReviewerCommandReviewer
type InviteReviewerCommandReviewer struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type _InviteReviewerCommandReviewer InviteReviewerCommandReviewer

// NewInviteReviewerCommandReviewer instantiates a new InviteReviewerCommandReviewer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteReviewerCommandReviewer(name string, email string) *InviteReviewerCommandReviewer {
	this := InviteReviewerCommandReviewer{}
	this.Name = name
	this.Email = email
	return &this
}

// NewInviteReviewerCommandReviewerWithDefaults instantiates a new InviteReviewerCommandReviewer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteReviewerCommandReviewerWithDefaults() *InviteReviewerCommandReviewer {
	this := InviteReviewerCommandReviewer{}
	return &this
}

// GetName returns the Name field value
func (o *InviteReviewerCommandReviewer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InviteReviewerCommandReviewer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InviteReviewerCommandReviewer) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *InviteReviewerCommandReviewer) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InviteReviewerCommandReviewer) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InviteReviewerCommandReviewer) SetEmail(v string) {
	o.Email = v
}

func (o InviteReviewerCommandReviewer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteReviewerCommandReviewer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *InviteReviewerCommandReviewer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteReviewerCommandReviewer := _InviteReviewerCommandReviewer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteReviewerCommandReviewer)

	if err != nil {
		return err
	}

	*o = InviteReviewerCommandReviewer(varInviteReviewerCommandReviewer)

	return err
}

type NullableInviteReviewerCommandReviewer struct {
	value *InviteReviewerCommandReviewer
	isSet bool
}

func (v NullableInviteReviewerCommandReviewer) Get() *InviteReviewerCommandReviewer {
	return v.value
}

func (v *NullableInviteReviewerCommandReviewer) Set(val *InviteReviewerCommandReviewer) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteReviewerCommandReviewer) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteReviewerCommandReviewer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteReviewerCommandReviewer(val *InviteReviewerCommandReviewer) *NullableInviteReviewerCommandReviewer {
	return &NullableInviteReviewerCommandReviewer{value: val, isSet: true}
}

func (v NullableInviteReviewerCommandReviewer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteReviewerCommandReviewer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
