/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
)

// checks if the Response8007Errors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response8007Errors{}

// Response8007Errors struct for Response8007Errors
type Response8007Errors struct {
	Organization      map[string]interface{}            `json:"organization,omitempty"`
	FormTitle         map[string]interface{}            `json:"form/title,omitempty"`
	FormInternalName  map[string]interface{}            `json:"form/internal-name,omitempty"`
	FormExternalTitle map[string]interface{}            `json:"form/external-title,omitempty"`
	FormFields        map[string]map[string]interface{} `json:"form/fields,omitempty"`
}

// NewResponse8007Errors instantiates a new Response8007Errors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse8007Errors() *Response8007Errors {
	this := Response8007Errors{}
	return &this
}

// NewResponse8007ErrorsWithDefaults instantiates a new Response8007Errors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse8007ErrorsWithDefaults() *Response8007Errors {
	this := Response8007Errors{}
	return &this
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *Response8007Errors) GetOrganization() map[string]interface{} {
	if o == nil || IsNil(o.Organization) {
		var ret map[string]interface{}
		return ret
	}
	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response8007Errors) GetOrganizationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Organization) {
		return map[string]interface{}{}, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *Response8007Errors) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given map[string]interface{} and assigns it to the Organization field.
func (o *Response8007Errors) SetOrganization(v map[string]interface{}) {
	o.Organization = v
}

// GetFormTitle returns the FormTitle field value if set, zero value otherwise.
func (o *Response8007Errors) GetFormTitle() map[string]interface{} {
	if o == nil || IsNil(o.FormTitle) {
		var ret map[string]interface{}
		return ret
	}
	return o.FormTitle
}

// GetFormTitleOk returns a tuple with the FormTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response8007Errors) GetFormTitleOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FormTitle) {
		return map[string]interface{}{}, false
	}
	return o.FormTitle, true
}

// HasFormTitle returns a boolean if a field has been set.
func (o *Response8007Errors) HasFormTitle() bool {
	if o != nil && !IsNil(o.FormTitle) {
		return true
	}

	return false
}

// SetFormTitle gets a reference to the given map[string]interface{} and assigns it to the FormTitle field.
func (o *Response8007Errors) SetFormTitle(v map[string]interface{}) {
	o.FormTitle = v
}

// GetFormInternalName returns the FormInternalName field value if set, zero value otherwise.
func (o *Response8007Errors) GetFormInternalName() map[string]interface{} {
	if o == nil || IsNil(o.FormInternalName) {
		var ret map[string]interface{}
		return ret
	}
	return o.FormInternalName
}

// GetFormInternalNameOk returns a tuple with the FormInternalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response8007Errors) GetFormInternalNameOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FormInternalName) {
		return map[string]interface{}{}, false
	}
	return o.FormInternalName, true
}

// HasFormInternalName returns a boolean if a field has been set.
func (o *Response8007Errors) HasFormInternalName() bool {
	if o != nil && !IsNil(o.FormInternalName) {
		return true
	}

	return false
}

// SetFormInternalName gets a reference to the given map[string]interface{} and assigns it to the FormInternalName field.
func (o *Response8007Errors) SetFormInternalName(v map[string]interface{}) {
	o.FormInternalName = v
}

// GetFormExternalTitle returns the FormExternalTitle field value if set, zero value otherwise.
func (o *Response8007Errors) GetFormExternalTitle() map[string]interface{} {
	if o == nil || IsNil(o.FormExternalTitle) {
		var ret map[string]interface{}
		return ret
	}
	return o.FormExternalTitle
}

// GetFormExternalTitleOk returns a tuple with the FormExternalTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response8007Errors) GetFormExternalTitleOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FormExternalTitle) {
		return map[string]interface{}{}, false
	}
	return o.FormExternalTitle, true
}

// HasFormExternalTitle returns a boolean if a field has been set.
func (o *Response8007Errors) HasFormExternalTitle() bool {
	if o != nil && !IsNil(o.FormExternalTitle) {
		return true
	}

	return false
}

// SetFormExternalTitle gets a reference to the given map[string]interface{} and assigns it to the FormExternalTitle field.
func (o *Response8007Errors) SetFormExternalTitle(v map[string]interface{}) {
	o.FormExternalTitle = v
}

// GetFormFields returns the FormFields field value if set, zero value otherwise.
func (o *Response8007Errors) GetFormFields() map[string]map[string]interface{} {
	if o == nil || IsNil(o.FormFields) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.FormFields
}

// GetFormFieldsOk returns a tuple with the FormFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response8007Errors) GetFormFieldsOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.FormFields) {
		return map[string]map[string]interface{}{}, false
	}
	return o.FormFields, true
}

// HasFormFields returns a boolean if a field has been set.
func (o *Response8007Errors) HasFormFields() bool {
	if o != nil && !IsNil(o.FormFields) {
		return true
	}

	return false
}

// SetFormFields gets a reference to the given map[string]map[string]interface{} and assigns it to the FormFields field.
func (o *Response8007Errors) SetFormFields(v map[string]map[string]interface{}) {
	o.FormFields = v
}

func (o Response8007Errors) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response8007Errors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.FormTitle) {
		toSerialize["form/title"] = o.FormTitle
	}
	if !IsNil(o.FormInternalName) {
		toSerialize["form/internal-name"] = o.FormInternalName
	}
	if !IsNil(o.FormExternalTitle) {
		toSerialize["form/external-title"] = o.FormExternalTitle
	}
	if !IsNil(o.FormFields) {
		toSerialize["form/fields"] = o.FormFields
	}
	return toSerialize, nil
}

type NullableResponse8007Errors struct {
	value *Response8007Errors
	isSet bool
}

func (v NullableResponse8007Errors) Get() *Response8007Errors {
	return v.value
}

func (v *NullableResponse8007Errors) Set(val *Response8007Errors) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse8007Errors) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse8007Errors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse8007Errors(val *Response8007Errors) *NullableResponse8007Errors {
	return &NullableResponse8007Errors{value: val, isSet: true}
}

func (v NullableResponse8007Errors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse8007Errors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
