/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FormTemplateFieldsVisibilityField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FormTemplateFieldsVisibilityField{}

// FormTemplateFieldsVisibilityField struct for FormTemplateFieldsVisibilityField
type FormTemplateFieldsVisibilityField struct {
	FieldId string `json:"field/id"`
}

type _FormTemplateFieldsVisibilityField FormTemplateFieldsVisibilityField

// NewFormTemplateFieldsVisibilityField instantiates a new FormTemplateFieldsVisibilityField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormTemplateFieldsVisibilityField(fieldId string) *FormTemplateFieldsVisibilityField {
	this := FormTemplateFieldsVisibilityField{}
	this.FieldId = fieldId
	return &this
}

// NewFormTemplateFieldsVisibilityFieldWithDefaults instantiates a new FormTemplateFieldsVisibilityField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormTemplateFieldsVisibilityFieldWithDefaults() *FormTemplateFieldsVisibilityField {
	this := FormTemplateFieldsVisibilityField{}
	return &this
}

// GetFieldId returns the FieldId field value
func (o *FormTemplateFieldsVisibilityField) GetFieldId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldId
}

// GetFieldIdOk returns a tuple with the FieldId field value
// and a boolean to check if the value has been set.
func (o *FormTemplateFieldsVisibilityField) GetFieldIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldId, true
}

// SetFieldId sets field value
func (o *FormTemplateFieldsVisibilityField) SetFieldId(v string) {
	o.FieldId = v
}

func (o FormTemplateFieldsVisibilityField) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FormTemplateFieldsVisibilityField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field/id"] = o.FieldId
	return toSerialize, nil
}

func (o *FormTemplateFieldsVisibilityField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field/id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFormTemplateFieldsVisibilityField := _FormTemplateFieldsVisibilityField{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFormTemplateFieldsVisibilityField)

	if err != nil {
		return err
	}

	*o = FormTemplateFieldsVisibilityField(varFormTemplateFieldsVisibilityField)

	return err
}

type NullableFormTemplateFieldsVisibilityField struct {
	value *FormTemplateFieldsVisibilityField
	isSet bool
}

func (v NullableFormTemplateFieldsVisibilityField) Get() *FormTemplateFieldsVisibilityField {
	return v.value
}

func (v *NullableFormTemplateFieldsVisibilityField) Set(val *FormTemplateFieldsVisibilityField) {
	v.value = val
	v.isSet = true
}

func (v NullableFormTemplateFieldsVisibilityField) IsSet() bool {
	return v.isSet
}

func (v *NullableFormTemplateFieldsVisibilityField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormTemplateFieldsVisibilityField(val *FormTemplateFieldsVisibilityField) *NullableFormTemplateFieldsVisibilityField {
	return &NullableFormTemplateFieldsVisibilityField{value: val, isSet: true}
}

func (v NullableFormTemplateFieldsVisibilityField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormTemplateFieldsVisibilityField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
