/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SaveDraftCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SaveDraftCommand{}

// SaveDraftCommand struct for SaveDraftCommand
type SaveDraftCommand struct {
	ApplicationId int64                         `json:"application-id"`
	FieldValues   []SaveDraftCommandFieldValues `json:"field-values"`
	DuoCodes      []DuoCode                     `json:"duo-codes,omitempty"`
}

type _SaveDraftCommand SaveDraftCommand

// NewSaveDraftCommand instantiates a new SaveDraftCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSaveDraftCommand(applicationId int64, fieldValues []SaveDraftCommandFieldValues) *SaveDraftCommand {
	this := SaveDraftCommand{}
	this.ApplicationId = applicationId
	this.FieldValues = fieldValues
	return &this
}

// NewSaveDraftCommandWithDefaults instantiates a new SaveDraftCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSaveDraftCommandWithDefaults() *SaveDraftCommand {
	this := SaveDraftCommand{}
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *SaveDraftCommand) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *SaveDraftCommand) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *SaveDraftCommand) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetFieldValues returns the FieldValues field value
func (o *SaveDraftCommand) GetFieldValues() []SaveDraftCommandFieldValues {
	if o == nil {
		var ret []SaveDraftCommandFieldValues
		return ret
	}

	return o.FieldValues
}

// GetFieldValuesOk returns a tuple with the FieldValues field value
// and a boolean to check if the value has been set.
func (o *SaveDraftCommand) GetFieldValuesOk() ([]SaveDraftCommandFieldValues, bool) {
	if o == nil {
		return nil, false
	}
	return o.FieldValues, true
}

// SetFieldValues sets field value
func (o *SaveDraftCommand) SetFieldValues(v []SaveDraftCommandFieldValues) {
	o.FieldValues = v
}

// GetDuoCodes returns the DuoCodes field value if set, zero value otherwise.
func (o *SaveDraftCommand) GetDuoCodes() []DuoCode {
	if o == nil || IsNil(o.DuoCodes) {
		var ret []DuoCode
		return ret
	}
	return o.DuoCodes
}

// GetDuoCodesOk returns a tuple with the DuoCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SaveDraftCommand) GetDuoCodesOk() ([]DuoCode, bool) {
	if o == nil || IsNil(o.DuoCodes) {
		return nil, false
	}
	return o.DuoCodes, true
}

// HasDuoCodes returns a boolean if a field has been set.
func (o *SaveDraftCommand) HasDuoCodes() bool {
	if o != nil && !IsNil(o.DuoCodes) {
		return true
	}

	return false
}

// SetDuoCodes gets a reference to the given []DuoCode and assigns it to the DuoCodes field.
func (o *SaveDraftCommand) SetDuoCodes(v []DuoCode) {
	o.DuoCodes = v
}

func (o SaveDraftCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SaveDraftCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["application-id"] = o.ApplicationId
	toSerialize["field-values"] = o.FieldValues
	if !IsNil(o.DuoCodes) {
		toSerialize["duo-codes"] = o.DuoCodes
	}
	return toSerialize, nil
}

func (o *SaveDraftCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"application-id",
		"field-values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSaveDraftCommand := _SaveDraftCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSaveDraftCommand)

	if err != nil {
		return err
	}

	*o = SaveDraftCommand(varSaveDraftCommand)

	return err
}

type NullableSaveDraftCommand struct {
	value *SaveDraftCommand
	isSet bool
}

func (v NullableSaveDraftCommand) Get() *SaveDraftCommand {
	return v.value
}

func (v *NullableSaveDraftCommand) Set(val *SaveDraftCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableSaveDraftCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableSaveDraftCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSaveDraftCommand(val *SaveDraftCommand) *NullableSaveDraftCommand {
	return &NullableSaveDraftCommand{value: val, isSet: true}
}

func (v NullableSaveDraftCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSaveDraftCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
