/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
)

// checks if the Response7820ProcessingState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7820ProcessingState{}

// Response7820ProcessingState struct for Response7820ProcessingState
type Response7820ProcessingState struct {
	Public  *ProcessingState `json:"public,omitempty"`
	Private *ProcessingState `json:"private,omitempty"`
}

// NewResponse7820ProcessingState instantiates a new Response7820ProcessingState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7820ProcessingState() *Response7820ProcessingState {
	this := Response7820ProcessingState{}
	return &this
}

// NewResponse7820ProcessingStateWithDefaults instantiates a new Response7820ProcessingState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7820ProcessingStateWithDefaults() *Response7820ProcessingState {
	this := Response7820ProcessingState{}
	return &this
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *Response7820ProcessingState) GetPublic() ProcessingState {
	if o == nil || IsNil(o.Public) {
		var ret ProcessingState
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response7820ProcessingState) GetPublicOk() (*ProcessingState, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *Response7820ProcessingState) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given ProcessingState and assigns it to the Public field.
func (o *Response7820ProcessingState) SetPublic(v ProcessingState) {
	o.Public = &v
}

// GetPrivate returns the Private field value if set, zero value otherwise.
func (o *Response7820ProcessingState) GetPrivate() ProcessingState {
	if o == nil || IsNil(o.Private) {
		var ret ProcessingState
		return ret
	}
	return *o.Private
}

// GetPrivateOk returns a tuple with the Private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response7820ProcessingState) GetPrivateOk() (*ProcessingState, bool) {
	if o == nil || IsNil(o.Private) {
		return nil, false
	}
	return o.Private, true
}

// HasPrivate returns a boolean if a field has been set.
func (o *Response7820ProcessingState) HasPrivate() bool {
	if o != nil && !IsNil(o.Private) {
		return true
	}

	return false
}

// SetPrivate gets a reference to the given ProcessingState and assigns it to the Private field.
func (o *Response7820ProcessingState) SetPrivate(v ProcessingState) {
	o.Private = &v
}

func (o Response7820ProcessingState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7820ProcessingState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	if !IsNil(o.Private) {
		toSerialize["private"] = o.Private
	}
	return toSerialize, nil
}

type NullableResponse7820ProcessingState struct {
	value *Response7820ProcessingState
	isSet bool
}

func (v NullableResponse7820ProcessingState) Get() *Response7820ProcessingState {
	return v.value
}

func (v *NullableResponse7820ProcessingState) Set(val *Response7820ProcessingState) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7820ProcessingState) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7820ProcessingState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7820ProcessingState(val *Response7820ProcessingState) *NullableResponse7820ProcessingState {
	return &NullableResponse7820ProcessingState{value: val, isSet: true}
}

func (v NullableResponse7820ProcessingState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7820ProcessingState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
