/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationRawBlacklistResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationRawBlacklistResource{}

// ApplicationRawBlacklistResource struct for ApplicationRawBlacklistResource
type ApplicationRawBlacklistResource struct {
	ResourceExtId string `json:"resource/ext-id"`
}

type _ApplicationRawBlacklistResource ApplicationRawBlacklistResource

// NewApplicationRawBlacklistResource instantiates a new ApplicationRawBlacklistResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationRawBlacklistResource(resourceExtId string) *ApplicationRawBlacklistResource {
	this := ApplicationRawBlacklistResource{}
	this.ResourceExtId = resourceExtId
	return &this
}

// NewApplicationRawBlacklistResourceWithDefaults instantiates a new ApplicationRawBlacklistResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationRawBlacklistResourceWithDefaults() *ApplicationRawBlacklistResource {
	this := ApplicationRawBlacklistResource{}
	return &this
}

// GetResourceExtId returns the ResourceExtId field value
func (o *ApplicationRawBlacklistResource) GetResourceExtId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceExtId
}

// GetResourceExtIdOk returns a tuple with the ResourceExtId field value
// and a boolean to check if the value has been set.
func (o *ApplicationRawBlacklistResource) GetResourceExtIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceExtId, true
}

// SetResourceExtId sets field value
func (o *ApplicationRawBlacklistResource) SetResourceExtId(v string) {
	o.ResourceExtId = v
}

func (o ApplicationRawBlacklistResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationRawBlacklistResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource/ext-id"] = o.ResourceExtId
	return toSerialize, nil
}

func (o *ApplicationRawBlacklistResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource/ext-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationRawBlacklistResource := _ApplicationRawBlacklistResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationRawBlacklistResource)

	if err != nil {
		return err
	}

	*o = ApplicationRawBlacklistResource(varApplicationRawBlacklistResource)

	return err
}

type NullableApplicationRawBlacklistResource struct {
	value *ApplicationRawBlacklistResource
	isSet bool
}

func (v NullableApplicationRawBlacklistResource) Get() *ApplicationRawBlacklistResource {
	return v.value
}

func (v *NullableApplicationRawBlacklistResource) Set(val *ApplicationRawBlacklistResource) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationRawBlacklistResource) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationRawBlacklistResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationRawBlacklistResource(val *ApplicationRawBlacklistResource) *NullableApplicationRawBlacklistResource {
	return &NullableApplicationRawBlacklistResource{value: val, isSet: true}
}

func (v NullableApplicationRawBlacklistResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationRawBlacklistResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
