/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationRawDuoMatchesValidation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationRawDuoMatchesValidation{}

// ApplicationRawDuoMatchesValidation struct for ApplicationRawDuoMatchesValidation
type ApplicationRawDuoMatchesValidation struct {
	Validity string                                     `json:"validity"`
	Errors   []ApplicationRawDuoMatchesValidationErrors `json:"errors,omitempty"`
}

type _ApplicationRawDuoMatchesValidation ApplicationRawDuoMatchesValidation

// NewApplicationRawDuoMatchesValidation instantiates a new ApplicationRawDuoMatchesValidation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationRawDuoMatchesValidation(validity string) *ApplicationRawDuoMatchesValidation {
	this := ApplicationRawDuoMatchesValidation{}
	this.Validity = validity
	return &this
}

// NewApplicationRawDuoMatchesValidationWithDefaults instantiates a new ApplicationRawDuoMatchesValidation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationRawDuoMatchesValidationWithDefaults() *ApplicationRawDuoMatchesValidation {
	this := ApplicationRawDuoMatchesValidation{}
	return &this
}

// GetValidity returns the Validity field value
func (o *ApplicationRawDuoMatchesValidation) GetValidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Validity
}

// GetValidityOk returns a tuple with the Validity field value
// and a boolean to check if the value has been set.
func (o *ApplicationRawDuoMatchesValidation) GetValidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Validity, true
}

// SetValidity sets field value
func (o *ApplicationRawDuoMatchesValidation) SetValidity(v string) {
	o.Validity = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ApplicationRawDuoMatchesValidation) GetErrors() []ApplicationRawDuoMatchesValidationErrors {
	if o == nil || IsNil(o.Errors) {
		var ret []ApplicationRawDuoMatchesValidationErrors
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationRawDuoMatchesValidation) GetErrorsOk() ([]ApplicationRawDuoMatchesValidationErrors, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ApplicationRawDuoMatchesValidation) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ApplicationRawDuoMatchesValidationErrors and assigns it to the Errors field.
func (o *ApplicationRawDuoMatchesValidation) SetErrors(v []ApplicationRawDuoMatchesValidationErrors) {
	o.Errors = v
}

func (o ApplicationRawDuoMatchesValidation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationRawDuoMatchesValidation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["validity"] = o.Validity
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *ApplicationRawDuoMatchesValidation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"validity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationRawDuoMatchesValidation := _ApplicationRawDuoMatchesValidation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationRawDuoMatchesValidation)

	if err != nil {
		return err
	}

	*o = ApplicationRawDuoMatchesValidation(varApplicationRawDuoMatchesValidation)

	return err
}

type NullableApplicationRawDuoMatchesValidation struct {
	value *ApplicationRawDuoMatchesValidation
	isSet bool
}

func (v NullableApplicationRawDuoMatchesValidation) Get() *ApplicationRawDuoMatchesValidation {
	return v.value
}

func (v *NullableApplicationRawDuoMatchesValidation) Set(val *ApplicationRawDuoMatchesValidation) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationRawDuoMatchesValidation) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationRawDuoMatchesValidation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationRawDuoMatchesValidation(val *ApplicationRawDuoMatchesValidation) *NullableApplicationRawDuoMatchesValidation {
	return &NullableApplicationRawDuoMatchesValidation{value: val, isSet: true}
}

func (v NullableApplicationRawDuoMatchesValidation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationRawDuoMatchesValidation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
