/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response7862ResourcesDuo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7862ResourcesDuo{}

// Response7862ResourcesDuo struct for Response7862ResourcesDuo
type Response7862ResourcesDuo struct {
	DuoCodes []DuoCodeFull `json:"duo/codes"`
}

type _Response7862ResourcesDuo Response7862ResourcesDuo

// NewResponse7862ResourcesDuo instantiates a new Response7862ResourcesDuo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7862ResourcesDuo(duoCodes []DuoCodeFull) *Response7862ResourcesDuo {
	this := Response7862ResourcesDuo{}
	this.DuoCodes = duoCodes
	return &this
}

// NewResponse7862ResourcesDuoWithDefaults instantiates a new Response7862ResourcesDuo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7862ResourcesDuoWithDefaults() *Response7862ResourcesDuo {
	this := Response7862ResourcesDuo{}
	return &this
}

// GetDuoCodes returns the DuoCodes field value
func (o *Response7862ResourcesDuo) GetDuoCodes() []DuoCodeFull {
	if o == nil {
		var ret []DuoCodeFull
		return ret
	}

	return o.DuoCodes
}

// GetDuoCodesOk returns a tuple with the DuoCodes field value
// and a boolean to check if the value has been set.
func (o *Response7862ResourcesDuo) GetDuoCodesOk() ([]DuoCodeFull, bool) {
	if o == nil {
		return nil, false
	}
	return o.DuoCodes, true
}

// SetDuoCodes sets field value
func (o *Response7862ResourcesDuo) SetDuoCodes(v []DuoCodeFull) {
	o.DuoCodes = v
}

func (o Response7862ResourcesDuo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7862ResourcesDuo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duo/codes"] = o.DuoCodes
	return toSerialize, nil
}

func (o *Response7862ResourcesDuo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duo/codes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse7862ResourcesDuo := _Response7862ResourcesDuo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse7862ResourcesDuo)

	if err != nil {
		return err
	}

	*o = Response7862ResourcesDuo(varResponse7862ResourcesDuo)

	return err
}

type NullableResponse7862ResourcesDuo struct {
	value *Response7862ResourcesDuo
	isSet bool
}

func (v NullableResponse7862ResourcesDuo) Get() *Response7862ResourcesDuo {
	return v.value
}

func (v *NullableResponse7862ResourcesDuo) Set(val *Response7862ResourcesDuo) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7862ResourcesDuo) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7862ResourcesDuo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7862ResourcesDuo(val *Response7862ResourcesDuo) *NullableResponse7862ResourcesDuo {
	return &NullableResponse7862ResourcesDuo{value: val, isSet: true}
}

func (v NullableResponse7862ResourcesDuo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7862ResourcesDuo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
