/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ResourceDuoCodesRestrictionsValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceDuoCodesRestrictionsValues{}

// ResourceDuoCodesRestrictionsValues struct for ResourceDuoCodesRestrictionsValues
type ResourceDuoCodesRestrictionsValues struct {
	Value string `json:"value"`
}

type _ResourceDuoCodesRestrictionsValues ResourceDuoCodesRestrictionsValues

// NewResourceDuoCodesRestrictionsValues instantiates a new ResourceDuoCodesRestrictionsValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceDuoCodesRestrictionsValues(value string) *ResourceDuoCodesRestrictionsValues {
	this := ResourceDuoCodesRestrictionsValues{}
	this.Value = value
	return &this
}

// NewResourceDuoCodesRestrictionsValuesWithDefaults instantiates a new ResourceDuoCodesRestrictionsValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceDuoCodesRestrictionsValuesWithDefaults() *ResourceDuoCodesRestrictionsValues {
	this := ResourceDuoCodesRestrictionsValues{}
	return &this
}

// GetValue returns the Value field value
func (o *ResourceDuoCodesRestrictionsValues) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ResourceDuoCodesRestrictionsValues) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ResourceDuoCodesRestrictionsValues) SetValue(v string) {
	o.Value = v
}

func (o ResourceDuoCodesRestrictionsValues) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceDuoCodesRestrictionsValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ResourceDuoCodesRestrictionsValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceDuoCodesRestrictionsValues := _ResourceDuoCodesRestrictionsValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourceDuoCodesRestrictionsValues)

	if err != nil {
		return err
	}

	*o = ResourceDuoCodesRestrictionsValues(varResourceDuoCodesRestrictionsValues)

	return err
}

type NullableResourceDuoCodesRestrictionsValues struct {
	value *ResourceDuoCodesRestrictionsValues
	isSet bool
}

func (v NullableResourceDuoCodesRestrictionsValues) Get() *ResourceDuoCodesRestrictionsValues {
	return v.value
}

func (v *NullableResourceDuoCodesRestrictionsValues) Set(val *ResourceDuoCodesRestrictionsValues) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceDuoCodesRestrictionsValues) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceDuoCodesRestrictionsValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceDuoCodesRestrictionsValues(val *ResourceDuoCodesRestrictionsValues) *NullableResourceDuoCodesRestrictionsValues {
	return &NullableResourceDuoCodesRestrictionsValues{value: val, isSet: true}
}

func (v NullableResourceDuoCodesRestrictionsValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceDuoCodesRestrictionsValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
