/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EditCatalogueItemCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditCatalogueItemCommand{}

// EditCatalogueItemCommand struct for EditCatalogueItemCommand
type EditCatalogueItemCommand struct {
	Id int64 `json:"id"`
	// Localizations keyed by language
	Localizations map[string]CatalogueItemLocalization `json:"localizations"`
	Organization  *OrganizationId                      `json:"organization,omitempty"`
	Categories    []CategoryId                         `json:"categories,omitempty"`
}

type _EditCatalogueItemCommand EditCatalogueItemCommand

// NewEditCatalogueItemCommand instantiates a new EditCatalogueItemCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditCatalogueItemCommand(id int64, localizations map[string]CatalogueItemLocalization) *EditCatalogueItemCommand {
	this := EditCatalogueItemCommand{}
	this.Id = id
	this.Localizations = localizations
	return &this
}

// NewEditCatalogueItemCommandWithDefaults instantiates a new EditCatalogueItemCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditCatalogueItemCommandWithDefaults() *EditCatalogueItemCommand {
	this := EditCatalogueItemCommand{}
	return &this
}

// GetId returns the Id field value
func (o *EditCatalogueItemCommand) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EditCatalogueItemCommand) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EditCatalogueItemCommand) SetId(v int64) {
	o.Id = v
}

// GetLocalizations returns the Localizations field value
func (o *EditCatalogueItemCommand) GetLocalizations() map[string]CatalogueItemLocalization {
	if o == nil {
		var ret map[string]CatalogueItemLocalization
		return ret
	}

	return o.Localizations
}

// GetLocalizationsOk returns a tuple with the Localizations field value
// and a boolean to check if the value has been set.
func (o *EditCatalogueItemCommand) GetLocalizationsOk() (*map[string]CatalogueItemLocalization, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Localizations, true
}

// SetLocalizations sets field value
func (o *EditCatalogueItemCommand) SetLocalizations(v map[string]CatalogueItemLocalization) {
	o.Localizations = v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *EditCatalogueItemCommand) GetOrganization() OrganizationId {
	if o == nil || IsNil(o.Organization) {
		var ret OrganizationId
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditCatalogueItemCommand) GetOrganizationOk() (*OrganizationId, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *EditCatalogueItemCommand) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given OrganizationId and assigns it to the Organization field.
func (o *EditCatalogueItemCommand) SetOrganization(v OrganizationId) {
	o.Organization = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *EditCatalogueItemCommand) GetCategories() []CategoryId {
	if o == nil || IsNil(o.Categories) {
		var ret []CategoryId
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditCatalogueItemCommand) GetCategoriesOk() ([]CategoryId, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *EditCatalogueItemCommand) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []CategoryId and assigns it to the Categories field.
func (o *EditCatalogueItemCommand) SetCategories(v []CategoryId) {
	o.Categories = v
}

func (o EditCatalogueItemCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditCatalogueItemCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["localizations"] = o.Localizations
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	return toSerialize, nil
}

func (o *EditCatalogueItemCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"localizations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEditCatalogueItemCommand := _EditCatalogueItemCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEditCatalogueItemCommand)

	if err != nil {
		return err
	}

	*o = EditCatalogueItemCommand(varEditCatalogueItemCommand)

	return err
}

type NullableEditCatalogueItemCommand struct {
	value *EditCatalogueItemCommand
	isSet bool
}

func (v NullableEditCatalogueItemCommand) Get() *EditCatalogueItemCommand {
	return v.value
}

func (v *NullableEditCatalogueItemCommand) Set(val *EditCatalogueItemCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableEditCatalogueItemCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableEditCatalogueItemCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditCatalogueItemCommand(val *EditCatalogueItemCommand) *NullableEditCatalogueItemCommand {
	return &NullableEditCatalogueItemCommand{value: val, isSet: true}
}

func (v NullableEditCatalogueItemCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditCatalogueItemCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
