/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationCopiedTo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationCopiedTo{}

// ApplicationCopiedTo struct for ApplicationCopiedTo
type ApplicationCopiedTo struct {
	ApplicationId         int64  `json:"application/id"`
	ApplicationExternalId string `json:"application/external-id"`
}

type _ApplicationCopiedTo ApplicationCopiedTo

// NewApplicationCopiedTo instantiates a new ApplicationCopiedTo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationCopiedTo(applicationId int64, applicationExternalId string) *ApplicationCopiedTo {
	this := ApplicationCopiedTo{}
	this.ApplicationId = applicationId
	this.ApplicationExternalId = applicationExternalId
	return &this
}

// NewApplicationCopiedToWithDefaults instantiates a new ApplicationCopiedTo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationCopiedToWithDefaults() *ApplicationCopiedTo {
	this := ApplicationCopiedTo{}
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *ApplicationCopiedTo) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *ApplicationCopiedTo) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *ApplicationCopiedTo) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetApplicationExternalId returns the ApplicationExternalId field value
func (o *ApplicationCopiedTo) GetApplicationExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationExternalId
}

// GetApplicationExternalIdOk returns a tuple with the ApplicationExternalId field value
// and a boolean to check if the value has been set.
func (o *ApplicationCopiedTo) GetApplicationExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationExternalId, true
}

// SetApplicationExternalId sets field value
func (o *ApplicationCopiedTo) SetApplicationExternalId(v string) {
	o.ApplicationExternalId = v
}

func (o ApplicationCopiedTo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationCopiedTo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["application/id"] = o.ApplicationId
	toSerialize["application/external-id"] = o.ApplicationExternalId
	return toSerialize, nil
}

func (o *ApplicationCopiedTo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"application/id",
		"application/external-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationCopiedTo := _ApplicationCopiedTo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationCopiedTo)

	if err != nil {
		return err
	}

	*o = ApplicationCopiedTo(varApplicationCopiedTo)

	return err
}

type NullableApplicationCopiedTo struct {
	value *ApplicationCopiedTo
	isSet bool
}

func (v NullableApplicationCopiedTo) Get() *ApplicationCopiedTo {
	return v.value
}

func (v *NullableApplicationCopiedTo) Set(val *ApplicationCopiedTo) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationCopiedTo) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationCopiedTo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationCopiedTo(val *ApplicationCopiedTo) *NullableApplicationCopiedTo {
	return &NullableApplicationCopiedTo{value: val, isSet: true}
}

func (v NullableApplicationCopiedTo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationCopiedTo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
