/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response6577Workflow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response6577Workflow{}

// Response6577Workflow struct for Response6577Workflow
type Response6577Workflow struct {
	WorkflowId                int64             `json:"workflow/id"`
	WorkflowType              string            `json:"workflow/type"`
	WorkflowDynamicHandlers   []Handler         `json:"workflow.dynamic/handlers,omitempty"`
	WorkflowVoting            *WorkflowVoting   `json:"workflow/voting,omitempty"`
	WorkflowAnonymizeHandling *bool             `json:"workflow/anonymize-handling,omitempty"`
	WorkflowProcessingStates  []ProcessingState `json:"workflow/processing-states,omitempty"`
}

type _Response6577Workflow Response6577Workflow

// NewResponse6577Workflow instantiates a new Response6577Workflow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse6577Workflow(workflowId int64, workflowType string) *Response6577Workflow {
	this := Response6577Workflow{}
	this.WorkflowId = workflowId
	this.WorkflowType = workflowType
	return &this
}

// NewResponse6577WorkflowWithDefaults instantiates a new Response6577Workflow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse6577WorkflowWithDefaults() *Response6577Workflow {
	this := Response6577Workflow{}
	return &this
}

// GetWorkflowId returns the WorkflowId field value
func (o *Response6577Workflow) GetWorkflowId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *Response6577Workflow) GetWorkflowIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *Response6577Workflow) SetWorkflowId(v int64) {
	o.WorkflowId = v
}

// GetWorkflowType returns the WorkflowType field value
func (o *Response6577Workflow) GetWorkflowType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowType
}

// GetWorkflowTypeOk returns a tuple with the WorkflowType field value
// and a boolean to check if the value has been set.
func (o *Response6577Workflow) GetWorkflowTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowType, true
}

// SetWorkflowType sets field value
func (o *Response6577Workflow) SetWorkflowType(v string) {
	o.WorkflowType = v
}

// GetWorkflowDynamicHandlers returns the WorkflowDynamicHandlers field value if set, zero value otherwise.
func (o *Response6577Workflow) GetWorkflowDynamicHandlers() []Handler {
	if o == nil || IsNil(o.WorkflowDynamicHandlers) {
		var ret []Handler
		return ret
	}
	return o.WorkflowDynamicHandlers
}

// GetWorkflowDynamicHandlersOk returns a tuple with the WorkflowDynamicHandlers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response6577Workflow) GetWorkflowDynamicHandlersOk() ([]Handler, bool) {
	if o == nil || IsNil(o.WorkflowDynamicHandlers) {
		return nil, false
	}
	return o.WorkflowDynamicHandlers, true
}

// HasWorkflowDynamicHandlers returns a boolean if a field has been set.
func (o *Response6577Workflow) HasWorkflowDynamicHandlers() bool {
	if o != nil && !IsNil(o.WorkflowDynamicHandlers) {
		return true
	}

	return false
}

// SetWorkflowDynamicHandlers gets a reference to the given []Handler and assigns it to the WorkflowDynamicHandlers field.
func (o *Response6577Workflow) SetWorkflowDynamicHandlers(v []Handler) {
	o.WorkflowDynamicHandlers = v
}

// GetWorkflowVoting returns the WorkflowVoting field value if set, zero value otherwise.
func (o *Response6577Workflow) GetWorkflowVoting() WorkflowVoting {
	if o == nil || IsNil(o.WorkflowVoting) {
		var ret WorkflowVoting
		return ret
	}
	return *o.WorkflowVoting
}

// GetWorkflowVotingOk returns a tuple with the WorkflowVoting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response6577Workflow) GetWorkflowVotingOk() (*WorkflowVoting, bool) {
	if o == nil || IsNil(o.WorkflowVoting) {
		return nil, false
	}
	return o.WorkflowVoting, true
}

// HasWorkflowVoting returns a boolean if a field has been set.
func (o *Response6577Workflow) HasWorkflowVoting() bool {
	if o != nil && !IsNil(o.WorkflowVoting) {
		return true
	}

	return false
}

// SetWorkflowVoting gets a reference to the given WorkflowVoting and assigns it to the WorkflowVoting field.
func (o *Response6577Workflow) SetWorkflowVoting(v WorkflowVoting) {
	o.WorkflowVoting = &v
}

// GetWorkflowAnonymizeHandling returns the WorkflowAnonymizeHandling field value if set, zero value otherwise.
func (o *Response6577Workflow) GetWorkflowAnonymizeHandling() bool {
	if o == nil || IsNil(o.WorkflowAnonymizeHandling) {
		var ret bool
		return ret
	}
	return *o.WorkflowAnonymizeHandling
}

// GetWorkflowAnonymizeHandlingOk returns a tuple with the WorkflowAnonymizeHandling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response6577Workflow) GetWorkflowAnonymizeHandlingOk() (*bool, bool) {
	if o == nil || IsNil(o.WorkflowAnonymizeHandling) {
		return nil, false
	}
	return o.WorkflowAnonymizeHandling, true
}

// HasWorkflowAnonymizeHandling returns a boolean if a field has been set.
func (o *Response6577Workflow) HasWorkflowAnonymizeHandling() bool {
	if o != nil && !IsNil(o.WorkflowAnonymizeHandling) {
		return true
	}

	return false
}

// SetWorkflowAnonymizeHandling gets a reference to the given bool and assigns it to the WorkflowAnonymizeHandling field.
func (o *Response6577Workflow) SetWorkflowAnonymizeHandling(v bool) {
	o.WorkflowAnonymizeHandling = &v
}

// GetWorkflowProcessingStates returns the WorkflowProcessingStates field value if set, zero value otherwise.
func (o *Response6577Workflow) GetWorkflowProcessingStates() []ProcessingState {
	if o == nil || IsNil(o.WorkflowProcessingStates) {
		var ret []ProcessingState
		return ret
	}
	return o.WorkflowProcessingStates
}

// GetWorkflowProcessingStatesOk returns a tuple with the WorkflowProcessingStates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response6577Workflow) GetWorkflowProcessingStatesOk() ([]ProcessingState, bool) {
	if o == nil || IsNil(o.WorkflowProcessingStates) {
		return nil, false
	}
	return o.WorkflowProcessingStates, true
}

// HasWorkflowProcessingStates returns a boolean if a field has been set.
func (o *Response6577Workflow) HasWorkflowProcessingStates() bool {
	if o != nil && !IsNil(o.WorkflowProcessingStates) {
		return true
	}

	return false
}

// SetWorkflowProcessingStates gets a reference to the given []ProcessingState and assigns it to the WorkflowProcessingStates field.
func (o *Response6577Workflow) SetWorkflowProcessingStates(v []ProcessingState) {
	o.WorkflowProcessingStates = v
}

func (o Response6577Workflow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response6577Workflow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workflow/id"] = o.WorkflowId
	toSerialize["workflow/type"] = o.WorkflowType
	if !IsNil(o.WorkflowDynamicHandlers) {
		toSerialize["workflow.dynamic/handlers"] = o.WorkflowDynamicHandlers
	}
	if !IsNil(o.WorkflowVoting) {
		toSerialize["workflow/voting"] = o.WorkflowVoting
	}
	if !IsNil(o.WorkflowAnonymizeHandling) {
		toSerialize["workflow/anonymize-handling"] = o.WorkflowAnonymizeHandling
	}
	if !IsNil(o.WorkflowProcessingStates) {
		toSerialize["workflow/processing-states"] = o.WorkflowProcessingStates
	}
	return toSerialize, nil
}

func (o *Response6577Workflow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workflow/id",
		"workflow/type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse6577Workflow := _Response6577Workflow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse6577Workflow)

	if err != nil {
		return err
	}

	*o = Response6577Workflow(varResponse6577Workflow)

	return err
}

type NullableResponse6577Workflow struct {
	value *Response6577Workflow
	isSet bool
}

func (v NullableResponse6577Workflow) Get() *Response6577Workflow {
	return v.value
}

func (v *NullableResponse6577Workflow) Set(val *Response6577Workflow) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse6577Workflow) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse6577Workflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse6577Workflow(val *Response6577Workflow) *NullableResponse6577Workflow {
	return &NullableResponse6577Workflow{value: val, isSet: true}
}

func (v NullableResponse6577Workflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse6577Workflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
