/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
)

// checks if the Response7799Duo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7799Duo{}

// Response7799Duo struct for Response7799Duo
type Response7799Duo struct {
	DuoCodes   []DuoCodeFull  `json:"duo/codes,omitempty"`
	DuoMatches []DuoCodeMatch `json:"duo/matches,omitempty"`
}

// NewResponse7799Duo instantiates a new Response7799Duo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7799Duo() *Response7799Duo {
	this := Response7799Duo{}
	return &this
}

// NewResponse7799DuoWithDefaults instantiates a new Response7799Duo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7799DuoWithDefaults() *Response7799Duo {
	this := Response7799Duo{}
	return &this
}

// GetDuoCodes returns the DuoCodes field value if set, zero value otherwise.
func (o *Response7799Duo) GetDuoCodes() []DuoCodeFull {
	if o == nil || IsNil(o.DuoCodes) {
		var ret []DuoCodeFull
		return ret
	}
	return o.DuoCodes
}

// GetDuoCodesOk returns a tuple with the DuoCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response7799Duo) GetDuoCodesOk() ([]DuoCodeFull, bool) {
	if o == nil || IsNil(o.DuoCodes) {
		return nil, false
	}
	return o.DuoCodes, true
}

// HasDuoCodes returns a boolean if a field has been set.
func (o *Response7799Duo) HasDuoCodes() bool {
	if o != nil && !IsNil(o.DuoCodes) {
		return true
	}

	return false
}

// SetDuoCodes gets a reference to the given []DuoCodeFull and assigns it to the DuoCodes field.
func (o *Response7799Duo) SetDuoCodes(v []DuoCodeFull) {
	o.DuoCodes = v
}

// GetDuoMatches returns the DuoMatches field value if set, zero value otherwise.
func (o *Response7799Duo) GetDuoMatches() []DuoCodeMatch {
	if o == nil || IsNil(o.DuoMatches) {
		var ret []DuoCodeMatch
		return ret
	}
	return o.DuoMatches
}

// GetDuoMatchesOk returns a tuple with the DuoMatches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response7799Duo) GetDuoMatchesOk() ([]DuoCodeMatch, bool) {
	if o == nil || IsNil(o.DuoMatches) {
		return nil, false
	}
	return o.DuoMatches, true
}

// HasDuoMatches returns a boolean if a field has been set.
func (o *Response7799Duo) HasDuoMatches() bool {
	if o != nil && !IsNil(o.DuoMatches) {
		return true
	}

	return false
}

// SetDuoMatches gets a reference to the given []DuoCodeMatch and assigns it to the DuoMatches field.
func (o *Response7799Duo) SetDuoMatches(v []DuoCodeMatch) {
	o.DuoMatches = v
}

func (o Response7799Duo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7799Duo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DuoCodes) {
		toSerialize["duo/codes"] = o.DuoCodes
	}
	if !IsNil(o.DuoMatches) {
		toSerialize["duo/matches"] = o.DuoMatches
	}
	return toSerialize, nil
}

type NullableResponse7799Duo struct {
	value *Response7799Duo
	isSet bool
}

func (v NullableResponse7799Duo) Get() *Response7799Duo {
	return v.value
}

func (v *NullableResponse7799Duo) Set(val *Response7799Duo) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7799Duo) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7799Duo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7799Duo(val *Response7799Duo) *NullableResponse7799Duo {
	return &NullableResponse7799Duo{value: val, isSet: true}
}

func (v NullableResponse7799Duo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7799Duo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
