/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
)

// checks if the GetConfigResponseExtraPagesTranslationsKeyword6530 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetConfigResponseExtraPagesTranslationsKeyword6530{}

// GetConfigResponseExtraPagesTranslationsKeyword6530 struct for GetConfigResponseExtraPagesTranslationsKeyword6530
type GetConfigResponseExtraPagesTranslationsKeyword6530 struct {
	Title    *string `json:"title,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Url      *string `json:"url,omitempty"`
}

// NewGetConfigResponseExtraPagesTranslationsKeyword6530 instantiates a new GetConfigResponseExtraPagesTranslationsKeyword6530 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConfigResponseExtraPagesTranslationsKeyword6530() *GetConfigResponseExtraPagesTranslationsKeyword6530 {
	this := GetConfigResponseExtraPagesTranslationsKeyword6530{}
	return &this
}

// NewGetConfigResponseExtraPagesTranslationsKeyword6530WithDefaults instantiates a new GetConfigResponseExtraPagesTranslationsKeyword6530 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConfigResponseExtraPagesTranslationsKeyword6530WithDefaults() *GetConfigResponseExtraPagesTranslationsKeyword6530 {
	this := GetConfigResponseExtraPagesTranslationsKeyword6530{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) SetTitle(v string) {
	o.Title = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) SetFilename(v string) {
	o.Filename = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GetConfigResponseExtraPagesTranslationsKeyword6530) SetUrl(v string) {
	o.Url = &v
}

func (o GetConfigResponseExtraPagesTranslationsKeyword6530) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetConfigResponseExtraPagesTranslationsKeyword6530) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableGetConfigResponseExtraPagesTranslationsKeyword6530 struct {
	value *GetConfigResponseExtraPagesTranslationsKeyword6530
	isSet bool
}

func (v NullableGetConfigResponseExtraPagesTranslationsKeyword6530) Get() *GetConfigResponseExtraPagesTranslationsKeyword6530 {
	return v.value
}

func (v *NullableGetConfigResponseExtraPagesTranslationsKeyword6530) Set(val *GetConfigResponseExtraPagesTranslationsKeyword6530) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConfigResponseExtraPagesTranslationsKeyword6530) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConfigResponseExtraPagesTranslationsKeyword6530) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConfigResponseExtraPagesTranslationsKeyword6530(val *GetConfigResponseExtraPagesTranslationsKeyword6530) *NullableGetConfigResponseExtraPagesTranslationsKeyword6530 {
	return &NullableGetConfigResponseExtraPagesTranslationsKeyword6530{value: val, isSet: true}
}

func (v NullableGetConfigResponseExtraPagesTranslationsKeyword6530) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConfigResponseExtraPagesTranslationsKeyword6530) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
