/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response7862InvitedMembers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7862InvitedMembers{}

// Response7862InvitedMembers struct for Response7862InvitedMembers
type Response7862InvitedMembers struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type _Response7862InvitedMembers Response7862InvitedMembers

// NewResponse7862InvitedMembers instantiates a new Response7862InvitedMembers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7862InvitedMembers(name string, email string) *Response7862InvitedMembers {
	this := Response7862InvitedMembers{}
	this.Name = name
	this.Email = email
	return &this
}

// NewResponse7862InvitedMembersWithDefaults instantiates a new Response7862InvitedMembers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7862InvitedMembersWithDefaults() *Response7862InvitedMembers {
	this := Response7862InvitedMembers{}
	return &this
}

// GetName returns the Name field value
func (o *Response7862InvitedMembers) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Response7862InvitedMembers) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Response7862InvitedMembers) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *Response7862InvitedMembers) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *Response7862InvitedMembers) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *Response7862InvitedMembers) SetEmail(v string) {
	o.Email = v
}

func (o Response7862InvitedMembers) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7862InvitedMembers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *Response7862InvitedMembers) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse7862InvitedMembers := _Response7862InvitedMembers{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse7862InvitedMembers)

	if err != nil {
		return err
	}

	*o = Response7862InvitedMembers(varResponse7862InvitedMembers)

	return err
}

type NullableResponse7862InvitedMembers struct {
	value *Response7862InvitedMembers
	isSet bool
}

func (v NullableResponse7862InvitedMembers) Get() *Response7862InvitedMembers {
	return v.value
}

func (v *NullableResponse7862InvitedMembers) Set(val *Response7862InvitedMembers) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7862InvitedMembers) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7862InvitedMembers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7862InvitedMembers(val *Response7862InvitedMembers) *NullableResponse7862InvitedMembers {
	return &NullableResponse7862InvitedMembers{value: val, isSet: true}
}

func (v NullableResponse7862InvitedMembers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7862InvitedMembers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
