/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response8021Workflow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response8021Workflow{}

// Response8021Workflow struct for Response8021Workflow
type Response8021Workflow struct {
	WorkflowId int64 `json:"workflow/id"`
}

type _Response8021Workflow Response8021Workflow

// NewResponse8021Workflow instantiates a new Response8021Workflow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse8021Workflow(workflowId int64) *Response8021Workflow {
	this := Response8021Workflow{}
	this.WorkflowId = workflowId
	return &this
}

// NewResponse8021WorkflowWithDefaults instantiates a new Response8021Workflow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse8021WorkflowWithDefaults() *Response8021Workflow {
	this := Response8021Workflow{}
	return &this
}

// GetWorkflowId returns the WorkflowId field value
func (o *Response8021Workflow) GetWorkflowId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *Response8021Workflow) GetWorkflowIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *Response8021Workflow) SetWorkflowId(v int64) {
	o.WorkflowId = v
}

func (o Response8021Workflow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response8021Workflow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workflow/id"] = o.WorkflowId
	return toSerialize, nil
}

func (o *Response8021Workflow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workflow/id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse8021Workflow := _Response8021Workflow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse8021Workflow)

	if err != nil {
		return err
	}

	*o = Response8021Workflow(varResponse8021Workflow)

	return err
}

type NullableResponse8021Workflow struct {
	value *Response8021Workflow
	isSet bool
}

func (v NullableResponse8021Workflow) Get() *Response8021Workflow {
	return v.value
}

func (v *NullableResponse8021Workflow) Set(val *Response8021Workflow) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse8021Workflow) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse8021Workflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse8021Workflow(val *Response8021Workflow) *NullableResponse8021Workflow {
	return &NullableResponse8021Workflow{value: val, isSet: true}
}

func (v NullableResponse8021Workflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse8021Workflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
