/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CatalogueItemLocalizationsKeyword6727 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogueItemLocalizationsKeyword6727{}

// CatalogueItemLocalizationsKeyword6727 struct for CatalogueItemLocalizationsKeyword6727
type CatalogueItemLocalizationsKeyword6727 struct {
	Id       int64          `json:"id"`
	Langcode string         `json:"langcode"`
	Title    string         `json:"title"`
	Infourl  NullableString `json:"infourl"`
}

type _CatalogueItemLocalizationsKeyword6727 CatalogueItemLocalizationsKeyword6727

// NewCatalogueItemLocalizationsKeyword6727 instantiates a new CatalogueItemLocalizationsKeyword6727 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogueItemLocalizationsKeyword6727(id int64, langcode string, title string, infourl NullableString) *CatalogueItemLocalizationsKeyword6727 {
	this := CatalogueItemLocalizationsKeyword6727{}
	this.Id = id
	this.Langcode = langcode
	this.Title = title
	this.Infourl = infourl
	return &this
}

// NewCatalogueItemLocalizationsKeyword6727WithDefaults instantiates a new CatalogueItemLocalizationsKeyword6727 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogueItemLocalizationsKeyword6727WithDefaults() *CatalogueItemLocalizationsKeyword6727 {
	this := CatalogueItemLocalizationsKeyword6727{}
	return &this
}

// GetId returns the Id field value
func (o *CatalogueItemLocalizationsKeyword6727) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CatalogueItemLocalizationsKeyword6727) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CatalogueItemLocalizationsKeyword6727) SetId(v int64) {
	o.Id = v
}

// GetLangcode returns the Langcode field value
func (o *CatalogueItemLocalizationsKeyword6727) GetLangcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Langcode
}

// GetLangcodeOk returns a tuple with the Langcode field value
// and a boolean to check if the value has been set.
func (o *CatalogueItemLocalizationsKeyword6727) GetLangcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Langcode, true
}

// SetLangcode sets field value
func (o *CatalogueItemLocalizationsKeyword6727) SetLangcode(v string) {
	o.Langcode = v
}

// GetTitle returns the Title field value
func (o *CatalogueItemLocalizationsKeyword6727) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CatalogueItemLocalizationsKeyword6727) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CatalogueItemLocalizationsKeyword6727) SetTitle(v string) {
	o.Title = v
}

// GetInfourl returns the Infourl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CatalogueItemLocalizationsKeyword6727) GetInfourl() string {
	if o == nil || o.Infourl.Get() == nil {
		var ret string
		return ret
	}

	return *o.Infourl.Get()
}

// GetInfourlOk returns a tuple with the Infourl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CatalogueItemLocalizationsKeyword6727) GetInfourlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Infourl.Get(), o.Infourl.IsSet()
}

// SetInfourl sets field value
func (o *CatalogueItemLocalizationsKeyword6727) SetInfourl(v string) {
	o.Infourl.Set(&v)
}

func (o CatalogueItemLocalizationsKeyword6727) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogueItemLocalizationsKeyword6727) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["langcode"] = o.Langcode
	toSerialize["title"] = o.Title
	toSerialize["infourl"] = o.Infourl.Get()
	return toSerialize, nil
}

func (o *CatalogueItemLocalizationsKeyword6727) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"langcode",
		"title",
		"infourl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogueItemLocalizationsKeyword6727 := _CatalogueItemLocalizationsKeyword6727{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogueItemLocalizationsKeyword6727)

	if err != nil {
		return err
	}

	*o = CatalogueItemLocalizationsKeyword6727(varCatalogueItemLocalizationsKeyword6727)

	return err
}

type NullableCatalogueItemLocalizationsKeyword6727 struct {
	value *CatalogueItemLocalizationsKeyword6727
	isSet bool
}

func (v NullableCatalogueItemLocalizationsKeyword6727) Get() *CatalogueItemLocalizationsKeyword6727 {
	return v.value
}

func (v *NullableCatalogueItemLocalizationsKeyword6727) Set(val *CatalogueItemLocalizationsKeyword6727) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogueItemLocalizationsKeyword6727) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogueItemLocalizationsKeyword6727) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogueItemLocalizationsKeyword6727(val *CatalogueItemLocalizationsKeyword6727) *NullableCatalogueItemLocalizationsKeyword6727 {
	return &NullableCatalogueItemLocalizationsKeyword6727{value: val, isSet: true}
}

func (v NullableCatalogueItemLocalizationsKeyword6727) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogueItemLocalizationsKeyword6727) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
