/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response7820AttachmentsEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7820AttachmentsEvent{}

// Response7820AttachmentsEvent struct for Response7820AttachmentsEvent
type Response7820AttachmentsEvent struct {
	EventId int64 `json:"event/id"`
}

type _Response7820AttachmentsEvent Response7820AttachmentsEvent

// NewResponse7820AttachmentsEvent instantiates a new Response7820AttachmentsEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7820AttachmentsEvent(eventId int64) *Response7820AttachmentsEvent {
	this := Response7820AttachmentsEvent{}
	this.EventId = eventId
	return &this
}

// NewResponse7820AttachmentsEventWithDefaults instantiates a new Response7820AttachmentsEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7820AttachmentsEventWithDefaults() *Response7820AttachmentsEvent {
	this := Response7820AttachmentsEvent{}
	return &this
}

// GetEventId returns the EventId field value
func (o *Response7820AttachmentsEvent) GetEventId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *Response7820AttachmentsEvent) GetEventIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *Response7820AttachmentsEvent) SetEventId(v int64) {
	o.EventId = v
}

func (o Response7820AttachmentsEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7820AttachmentsEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event/id"] = o.EventId
	return toSerialize, nil
}

func (o *Response7820AttachmentsEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event/id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse7820AttachmentsEvent := _Response7820AttachmentsEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse7820AttachmentsEvent)

	if err != nil {
		return err
	}

	*o = Response7820AttachmentsEvent(varResponse7820AttachmentsEvent)

	return err
}

type NullableResponse7820AttachmentsEvent struct {
	value *Response7820AttachmentsEvent
	isSet bool
}

func (v NullableResponse7820AttachmentsEvent) Get() *Response7820AttachmentsEvent {
	return v.value
}

func (v *NullableResponse7820AttachmentsEvent) Set(val *Response7820AttachmentsEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7820AttachmentsEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7820AttachmentsEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7820AttachmentsEvent(val *Response7820AttachmentsEvent) *NullableResponse7820AttachmentsEvent {
	return &NullableResponse7820AttachmentsEvent{value: val, isSet: true}
}

func (v NullableResponse7820AttachmentsEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7820AttachmentsEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
