/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FieldTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldTemplate{}

// FieldTemplate struct for FieldTemplate
type FieldTemplate struct {
	// Text values keyed by languages
	FieldInfoText *map[string]string `json:"field/info-text,omitempty"`
	// Text values keyed by languages
	FieldTitle     map[string]string           `json:"field/title"`
	FieldColumns   []FormTemplateFieldsColumns `json:"field/columns,omitempty"`
	FieldMaxLength NullableInt64               `json:"field/max-length,omitempty"`
	FieldOptions   []FormTemplateFieldsOptions `json:"field/options,omitempty"`
	// Public by default
	FieldPrivacy    *string                       `json:"field/privacy,omitempty"`
	FieldVisibility *FormTemplateFieldsVisibility `json:"field/visibility,omitempty"`
	FieldType       string                        `json:"field/type"`
	FieldId         string                        `json:"field/id"`
	FieldOptional   bool                          `json:"field/optional"`
	// Text values keyed by languages
	FieldPlaceholder *map[string]string `json:"field/placeholder,omitempty"`
}

type _FieldTemplate FieldTemplate

// NewwFieldTemplate instantiates a new FieldTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldTemplate(fieldTitle map[string]string, fieldType string, fieldId string, fieldOptional bool) *FieldTemplate {
	this := FieldTemplate{}
	this.FieldTitle = fieldTitle
	this.FieldType = fieldType
	this.FieldId = fieldId
	this.FieldOptional = fieldOptional
	return &this
}

// NewFieldTemplateWithDefaults instantiates a new FieldTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldTemplateWithDefaults() *FieldTemplate {
	this := FieldTemplate{}
	return &this
}

// GetFieldInfoText returns the FieldInfoText field value if set, zero value otherwise.
func (o *FieldTemplate) GetFieldInfoText() map[string]string {
	if o == nil || IsNil(o.FieldInfoText) {
		var ret map[string]string
		return ret
	}
	return *o.FieldInfoText
}

// GetFieldInfoTextOk returns a tuple with the FieldInfoText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldInfoTextOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.FieldInfoText) {
		return nil, false
	}
	return o.FieldInfoText, true
}

// HasFieldInfoText returns a boolean if a field has been set.
func (o *FieldTemplate) HasFieldInfoText() bool {
	if o != nil && !IsNil(o.FieldInfoText) {
		return true
	}

	return false
}

// SetFieldInfoText gets a reference to the given map[string]string and assigns it to the FieldInfoText field.
func (o *FieldTemplate) SetFieldInfoText(v map[string]string) {
	o.FieldInfoText = &v
}

// GetFieldTitle returns the FieldTitle field value
func (o *FieldTemplate) GetFieldTitle() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.FieldTitle
}

// GetFieldTitleOk returns a tuple with the FieldTitle field value
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldTitleOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldTitle, true
}

// SetFieldTitle sets field value
func (o *FieldTemplate) SetFieldTitle(v map[string]string) {
	o.FieldTitle = v
}

// GetFieldColumns returns the FieldColumns field value if set, zero value otherwise.
func (o *FieldTemplate) GetFieldColumns() []FormTemplateFieldsColumns {
	if o == nil || IsNil(o.FieldColumns) {
		var ret []FormTemplateFieldsColumns
		return ret
	}
	return o.FieldColumns
}

// GetFieldColumnsOk returns a tuple with the FieldColumns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldColumnsOk() ([]FormTemplateFieldsColumns, bool) {
	if o == nil || IsNil(o.FieldColumns) {
		return nil, false
	}
	return o.FieldColumns, true
}

// HasFieldColumns returns a boolean if a field has been set.
func (o *FieldTemplate) HasFieldColumns() bool {
	if o != nil && !IsNil(o.FieldColumns) {
		return true
	}

	return false
}

// SetFieldColumns gets a reference to the given []FormTemplateFieldsColumns and assigns it to the FieldColumns field.
func (o *FieldTemplate) SetFieldColumns(v []FormTemplateFieldsColumns) {
	o.FieldColumns = v
}

// GetFieldMaxLength returns the FieldMaxLength field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FieldTemplate) GetFieldMaxLength() int64 {
	if o == nil || IsNil(o.FieldMaxLength.Get()) {
		var ret int64
		return ret
	}
	return *o.FieldMaxLength.Get()
}

// GetFieldMaxLengthOk returns a tuple with the FieldMaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FieldTemplate) GetFieldMaxLengthOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.FieldMaxLength.Get(), o.FieldMaxLength.IsSet()
}

// HasFieldMaxLength returns a boolean if a field has been set.
func (o *FieldTemplate) HasFieldMaxLength() bool {
	if o != nil && o.FieldMaxLength.IsSet() {
		return true
	}

	return false
}

// SetFieldMaxLength gets a reference to the given NullableInt64 and assigns it to the FieldMaxLength field.
func (o *FieldTemplate) SetFieldMaxLength(v int64) {
	o.FieldMaxLength.Set(&v)
}

// SetFieldMaxLengthNil sets the value for FieldMaxLength to be an explicit nil
func (o *FieldTemplate) SetFieldMaxLengthNil() {
	o.FieldMaxLength.Set(nil)
}

// UnsetFieldMaxLength ensures that no value is present for FieldMaxLength, not even an explicit nil
func (o *FieldTemplate) UnsetFieldMaxLength() {
	o.FieldMaxLength.Unset()
}

// GetFieldOptions returns the FieldOptions field value if set, zero value otherwise.
func (o *FieldTemplate) GetFieldOptions() []FormTemplateFieldsOptions {
	if o == nil || IsNil(o.FieldOptions) {
		var ret []FormTemplateFieldsOptions
		return ret
	}
	return o.FieldOptions
}

// GetFieldOptionsOk returns a tuple with the FieldOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldOptionsOk() ([]FormTemplateFieldsOptions, bool) {
	if o == nil || IsNil(o.FieldOptions) {
		return nil, false
	}
	return o.FieldOptions, true
}

// HasFieldOptions returns a boolean if a field has been set.
func (o *FieldTemplate) HasFieldOptions() bool {
	if o != nil && !IsNil(o.FieldOptions) {
		return true
	}

	return false
}

// SetFieldOptions gets a reference to the given []FormTemplateFieldsOptions and assigns it to the FieldOptions field.
func (o *FieldTemplate) SetFieldOptions(v []FormTemplateFieldsOptions) {
	o.FieldOptions = v
}

// GetFieldPrivacy returns the FieldPrivacy field value if set, zero value otherwise.
func (o *FieldTemplate) GetFieldPrivacy() string {
	if o == nil || IsNil(o.FieldPrivacy) {
		var ret string
		return ret
	}
	return *o.FieldPrivacy
}

// GetFieldPrivacyOk returns a tuple with the FieldPrivacy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldPrivacyOk() (*string, bool) {
	if o == nil || IsNil(o.FieldPrivacy) {
		return nil, false
	}
	return o.FieldPrivacy, true
}

// HasFieldPrivacy returns a boolean if a field has been set.
func (o *FieldTemplate) HasFieldPrivacy() bool {
	if o != nil && !IsNil(o.FieldPrivacy) {
		return true
	}

	return false
}

// SetFieldPrivacy gets a reference to the given string and assigns it to the FieldPrivacy field.
func (o *FieldTemplate) SetFieldPrivacy(v string) {
	o.FieldPrivacy = &v
}

// GetFieldVisibility returns the FieldVisibility field value if set, zero value otherwise.
func (o *FieldTemplate) GetFieldVisibility() FormTemplateFieldsVisibility {
	if o == nil || IsNil(o.FieldVisibility) {
		var ret FormTemplateFieldsVisibility
		return ret
	}
	return *o.FieldVisibility
}

// GetFieldVisibilityOk returns a tuple with the FieldVisibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldVisibilityOk() (*FormTemplateFieldsVisibility, bool) {
	if o == nil || IsNil(o.FieldVisibility) {
		return nil, false
	}
	return o.FieldVisibility, true
}

// HasFieldVisibility returns a boolean if a field has been set.
func (o *FieldTemplate) HasFieldVisibility() bool {
	if o != nil && !IsNil(o.FieldVisibility) {
		return true
	}

	return false
}

// SetFieldVisibility gets a reference to the given FormTemplateFieldsVisibility and assigns it to the FieldVisibility field.
func (o *FieldTemplate) SetFieldVisibility(v FormTemplateFieldsVisibility) {
	o.FieldVisibility = &v
}

// GetFieldType returns the FieldType field value
func (o *FieldTemplate) GetFieldType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldType, true
}

// SetFieldType sets field value
func (o *FieldTemplate) SetFieldType(v string) {
	o.FieldType = v
}

// GetFieldId returns the FieldId field value
func (o *FieldTemplate) GetFieldId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldId
}

// GetFieldIdOk returns a tuple with the FieldId field value
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldId, true
}

// SetFieldId sets field value
func (o *FieldTemplate) SetFieldId(v string) {
	o.FieldId = v
}

// GetFieldOptional returns the FieldOptional field value
func (o *FieldTemplate) GetFieldOptional() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FieldOptional
}

// GetFieldOptionalOk returns a tuple with the FieldOptional field value
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldOptionalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldOptional, true
}

// SetFieldOptional sets field value
func (o *FieldTemplate) SetFieldOptional(v bool) {
	o.FieldOptional = v
}

// GetFieldPlaceholder returns the FieldPlaceholder field value if set, zero value otherwise.
func (o *FieldTemplate) GetFieldPlaceholder() map[string]string {
	if o == nil || IsNil(o.FieldPlaceholder) {
		var ret map[string]string
		return ret
	}
	return *o.FieldPlaceholder
}

// GetFieldPlaceholderOk returns a tuple with the FieldPlaceholder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldTemplate) GetFieldPlaceholderOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.FieldPlaceholder) {
		return nil, false
	}
	return o.FieldPlaceholder, true
}

// HasFieldPlaceholder returns a boolean if a field has been set.
func (o *FieldTemplate) HasFieldPlaceholder() bool {
	if o != nil && !IsNil(o.FieldPlaceholder) {
		return true
	}

	return false
}

// SetFieldPlaceholder gets a reference to the given map[string]string and assigns it to the FieldPlaceholder field.
func (o *FieldTemplate) SetFieldPlaceholder(v map[string]string) {
	o.FieldPlaceholder = &v
}

func (o FieldTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FieldInfoText) {
		toSerialize["field/info-text"] = o.FieldInfoText
	}
	toSerialize["field/title"] = o.FieldTitle
	if !IsNil(o.FieldColumns) {
		toSerialize["field/columns"] = o.FieldColumns
	}
	if o.FieldMaxLength.IsSet() {
		toSerialize["field/max-length"] = o.FieldMaxLength.Get()
	}
	if !IsNil(o.FieldOptions) {
		toSerialize["field/options"] = o.FieldOptions
	}
	if !IsNil(o.FieldPrivacy) {
		toSerialize["field/privacy"] = o.FieldPrivacy
	}
	if !IsNil(o.FieldVisibility) {
		toSerialize["field/visibility"] = o.FieldVisibility
	}
	toSerialize["field/type"] = o.FieldType
	toSerialize["field/id"] = o.FieldId
	toSerialize["field/optional"] = o.FieldOptional
	if !IsNil(o.FieldPlaceholder) {
		toSerialize["field/placeholder"] = o.FieldPlaceholder
	}
	return toSerialize, nil
}

func (o *FieldTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field/title",
		"field/type",
		"field/id",
		"field/optional",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldTemplate := _FieldTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldTemplate)

	if err != nil {
		return err
	}

	*o = FieldTemplate(varFieldTemplate)

	return err
}

type NullableFieldTemplate struct {
	value *FieldTemplate
	isSet bool
}

func (v NullableFieldTemplate) Get() *FieldTemplate {
	return v.value
}

func (v *NullableFieldTemplate) Set(val *FieldTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldTemplate(val *FieldTemplate) *NullableFieldTemplate {
	return &NullableFieldTemplate{value: val, isSet: true}
}

func (v NullableFieldTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
