/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOrganizationCommandReviewEmails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationCommandReviewEmails{}

// CreateOrganizationCommandReviewEmails struct for CreateOrganizationCommandReviewEmails
type CreateOrganizationCommandReviewEmails struct {
	// Text values keyed by languages
	Name  map[string]string `json:"name"`
	Email string            `json:"email"`
}

type _CreateOrganizationCommandReviewEmails CreateOrganizationCommandReviewEmails

// NewCreateOrganizationCommandReviewEmails instantiates a new CreateOrganizationCommandReviewEmails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationCommandReviewEmails(name map[string]string, email string) *CreateOrganizationCommandReviewEmails {
	this := CreateOrganizationCommandReviewEmails{}
	this.Name = name
	this.Email = email
	return &this
}

// NewCreateOrganizationCommandReviewEmailsWithDefaults instantiates a new CreateOrganizationCommandReviewEmails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationCommandReviewEmailsWithDefaults() *CreateOrganizationCommandReviewEmails {
	this := CreateOrganizationCommandReviewEmails{}
	return &this
}

// GetName returns the Name field value
func (o *CreateOrganizationCommandReviewEmails) GetName() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommandReviewEmails) GetNameOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateOrganizationCommandReviewEmails) SetName(v map[string]string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *CreateOrganizationCommandReviewEmails) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommandReviewEmails) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CreateOrganizationCommandReviewEmails) SetEmail(v string) {
	o.Email = v
}

func (o CreateOrganizationCommandReviewEmails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationCommandReviewEmails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *CreateOrganizationCommandReviewEmails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrganizationCommandReviewEmails := _CreateOrganizationCommandReviewEmails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrganizationCommandReviewEmails)

	if err != nil {
		return err
	}

	*o = CreateOrganizationCommandReviewEmails(varCreateOrganizationCommandReviewEmails)

	return err
}

type NullableCreateOrganizationCommandReviewEmails struct {
	value *CreateOrganizationCommandReviewEmails
	isSet bool
}

func (v NullableCreateOrganizationCommandReviewEmails) Get() *CreateOrganizationCommandReviewEmails {
	return v.value
}

func (v *NullableCreateOrganizationCommandReviewEmails) Set(val *CreateOrganizationCommandReviewEmails) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationCommandReviewEmails) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationCommandReviewEmails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationCommandReviewEmails(val *CreateOrganizationCommandReviewEmails) *NullableCreateOrganizationCommandReviewEmails {
	return &NullableCreateOrganizationCommandReviewEmails{value: val, isSet: true}
}

func (v NullableCreateOrganizationCommandReviewEmails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationCommandReviewEmails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
