/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Form type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Form{}

// Form struct for Form
type Form struct {
	FormId int64 `json:"form/id"`
	// DEPRECATED, will disappear, use either internal name or external title as you need
	FormTitle        *string `json:"form/title,omitempty"`
	FormInternalName string  `json:"form/internal-name"`
	// Text values keyed by languages
	FormExternalTitle map[string]string `json:"form/external-title"`
	FormFields        []Field           `json:"form/fields"`
}

type _Form Form

// NewForm instantiates a new Form object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForm(formId int64, formInternalName string, formExternalTitle map[string]string, formFields []Field) *Form {
	this := Form{}
	this.FormId = formId
	this.FormInternalName = formInternalName
	this.FormExternalTitle = formExternalTitle
	this.FormFields = formFields
	return &this
}

// NewFormWithDefaults instantiates a new Form object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormWithDefaults() *Form {
	this := Form{}
	return &this
}

// GetFormId returns the FormId field value
func (o *Form) GetFormId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FormId
}

// GetFormIdOk returns a tuple with the FormId field value
// and a boolean to check if the value has been set.
func (o *Form) GetFormIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormId, true
}

// SetFormId sets field value
func (o *Form) SetFormId(v int64) {
	o.FormId = v
}

// GetFormTitle returns the FormTitle field value if set, zero value otherwise.
func (o *Form) GetFormTitle() string {
	if o == nil || IsNil(o.FormTitle) {
		var ret string
		return ret
	}
	return *o.FormTitle
}

// GetFormTitleOk returns a tuple with the FormTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Form) GetFormTitleOk() (*string, bool) {
	if o == nil || IsNil(o.FormTitle) {
		return nil, false
	}
	return o.FormTitle, true
}

// HasFormTitle returns a boolean if a field has been set.
func (o *Form) HasFormTitle() bool {
	if o != nil && !IsNil(o.FormTitle) {
		return true
	}

	return false
}

// SetFormTitle gets a reference to the given string and assigns it to the FormTitle field.
func (o *Form) SetFormTitle(v string) {
	o.FormTitle = &v
}

// GetFormInternalName returns the FormInternalName field value
func (o *Form) GetFormInternalName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FormInternalName
}

// GetFormInternalNameOk returns a tuple with the FormInternalName field value
// and a boolean to check if the value has been set.
func (o *Form) GetFormInternalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormInternalName, true
}

// SetFormInternalName sets field value
func (o *Form) SetFormInternalName(v string) {
	o.FormInternalName = v
}

// GetFormExternalTitle returns the FormExternalTitle field value
func (o *Form) GetFormExternalTitle() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.FormExternalTitle
}

// GetFormExternalTitleOk returns a tuple with the FormExternalTitle field value
// and a boolean to check if the value has been set.
func (o *Form) GetFormExternalTitleOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormExternalTitle, true
}

// SetFormExternalTitle sets field value
func (o *Form) SetFormExternalTitle(v map[string]string) {
	o.FormExternalTitle = v
}

// GetFormFields returns the FormFields field value
func (o *Form) GetFormFields() []Field {
	if o == nil {
		var ret []Field
		return ret
	}

	return o.FormFields
}

// GetFormFieldsOk returns a tuple with the FormFields field value
// and a boolean to check if the value has been set.
func (o *Form) GetFormFieldsOk() ([]Field, bool) {
	if o == nil {
		return nil, false
	}
	return o.FormFields, true
}

// SetFormFields sets field value
func (o *Form) SetFormFields(v []Field) {
	o.FormFields = v
}

func (o Form) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Form) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["form/id"] = o.FormId
	if !IsNil(o.FormTitle) {
		toSerialize["form/title"] = o.FormTitle
	}
	toSerialize["form/internal-name"] = o.FormInternalName
	toSerialize["form/external-title"] = o.FormExternalTitle
	toSerialize["form/fields"] = o.FormFields
	return toSerialize, nil
}

func (o *Form) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"form/id",
		"form/internal-name",
		"form/external-title",
		"form/fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForm := _Form{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForm)

	if err != nil {
		return err
	}

	*o = Form(varForm)

	return err
}

type NullableForm struct {
	value *Form
	isSet bool
}

func (v NullableForm) Get() *Form {
	return v.value
}

func (v *NullableForm) Set(val *Form) {
	v.value = val
	v.isSet = true
}

func (v NullableForm) IsSet() bool {
	return v.isSet
}

func (v *NullableForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForm(val *Form) *NullableForm {
	return &NullableForm{value: val, isSet: true}
}

func (v NullableForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
