/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CreateOrganizationCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationCommand{}

// CreateOrganizationCommand struct for CreateOrganizationCommand
type CreateOrganizationCommand struct {
	Archived       *bool  `json:"archived,omitempty"`
	OrganizationId string `json:"organization/id"`
	// Text values keyed by languages
	OrganizationShortName    map[string]string                       `json:"organization/short-name"`
	OrganizationReviewEmails []CreateOrganizationCommandReviewEmails `json:"organization/review-emails,omitempty"`
	Enabled                  *bool                                   `json:"enabled,omitempty"`
	OrganizationOwners       []User                                  `json:"organization/owners,omitempty"`
	OrganizationModifier     *UserWithAttributes                     `json:"organization/modifier,omitempty"`
	OrganizationLastModified *time.Time                              `json:"organization/last-modified,omitempty"`
	// Text values keyed by languages
	OrganizationName map[string]string `json:"organization/name"`
}

type _CreateOrganizationCommand CreateOrganizationCommand

// NewCreateOrganizationCommand instantiates a new CreateOrganizationCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationCommand(organizationId string, organizationShortName map[string]string, organizationName map[string]string) *CreateOrganizationCommand {
	this := CreateOrganizationCommand{}
	this.OrganizationId = organizationId
	this.OrganizationShortName = organizationShortName
	this.OrganizationName = organizationName
	return &this
}

// NewCreateOrganizationCommandWithDefaults instantiates a new CreateOrganizationCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationCommandWithDefaults() *CreateOrganizationCommand {
	this := CreateOrganizationCommand{}
	return &this
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *CreateOrganizationCommand) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *CreateOrganizationCommand) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *CreateOrganizationCommand) SetArchived(v bool) {
	o.Archived = &v
}

// GetOrganizationId returns the OrganizationId field value
func (o *CreateOrganizationCommand) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *CreateOrganizationCommand) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetOrganizationShortName returns the OrganizationShortName field value
func (o *CreateOrganizationCommand) GetOrganizationShortName() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.OrganizationShortName
}

// GetOrganizationShortNameOk returns a tuple with the OrganizationShortName field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetOrganizationShortNameOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationShortName, true
}

// SetOrganizationShortName sets field value
func (o *CreateOrganizationCommand) SetOrganizationShortName(v map[string]string) {
	o.OrganizationShortName = v
}

// GetOrganizationReviewEmails returns the OrganizationReviewEmails field value if set, zero value otherwise.
func (o *CreateOrganizationCommand) GetOrganizationReviewEmails() []CreateOrganizationCommandReviewEmails {
	if o == nil || IsNil(o.OrganizationReviewEmails) {
		var ret []CreateOrganizationCommandReviewEmails
		return ret
	}
	return o.OrganizationReviewEmails
}

// GetOrganizationReviewEmailsOk returns a tuple with the OrganizationReviewEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetOrganizationReviewEmailsOk() ([]CreateOrganizationCommandReviewEmails, bool) {
	if o == nil || IsNil(o.OrganizationReviewEmails) {
		return nil, false
	}
	return o.OrganizationReviewEmails, true
}

// HasOrganizationReviewEmails returns a boolean if a field has been set.
func (o *CreateOrganizationCommand) HasOrganizationReviewEmails() bool {
	if o != nil && !IsNil(o.OrganizationReviewEmails) {
		return true
	}

	return false
}

// SetOrganizationReviewEmails gets a reference to the given []CreateOrganizationCommandReviewEmails and assigns it to the OrganizationReviewEmails field.
func (o *CreateOrganizationCommand) SetOrganizationReviewEmails(v []CreateOrganizationCommandReviewEmails) {
	o.OrganizationReviewEmails = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateOrganizationCommand) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateOrganizationCommand) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateOrganizationCommand) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetOrganizationOwners returns the OrganizationOwners field value if set, zero value otherwise.
func (o *CreateOrganizationCommand) GetOrganizationOwners() []User {
	if o == nil || IsNil(o.OrganizationOwners) {
		var ret []User
		return ret
	}
	return o.OrganizationOwners
}

// GetOrganizationOwnersOk returns a tuple with the OrganizationOwners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetOrganizationOwnersOk() ([]User, bool) {
	if o == nil || IsNil(o.OrganizationOwners) {
		return nil, false
	}
	return o.OrganizationOwners, true
}

// HasOrganizationOwners returns a boolean if a field has been set.
func (o *CreateOrganizationCommand) HasOrganizationOwners() bool {
	if o != nil && !IsNil(o.OrganizationOwners) {
		return true
	}

	return false
}

// SetOrganizationOwners gets a reference to the given []User and assigns it to the OrganizationOwners field.
func (o *CreateOrganizationCommand) SetOrganizationOwners(v []User) {
	o.OrganizationOwners = v
}

// GetOrganizationModifier returns the OrganizationModifier field value if set, zero value otherwise.
func (o *CreateOrganizationCommand) GetOrganizationModifier() UserWithAttributes {
	if o == nil || IsNil(o.OrganizationModifier) {
		var ret UserWithAttributes
		return ret
	}
	return *o.OrganizationModifier
}

// GetOrganizationModifierOk returns a tuple with the OrganizationModifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetOrganizationModifierOk() (*UserWithAttributes, bool) {
	if o == nil || IsNil(o.OrganizationModifier) {
		return nil, false
	}
	return o.OrganizationModifier, true
}

// HasOrganizationModifier returns a boolean if a field has been set.
func (o *CreateOrganizationCommand) HasOrganizationModifier() bool {
	if o != nil && !IsNil(o.OrganizationModifier) {
		return true
	}

	return false
}

// SetOrganizationModifier gets a reference to the given UserWithAttributes and assigns it to the OrganizationModifier field.
func (o *CreateOrganizationCommand) SetOrganizationModifier(v UserWithAttributes) {
	o.OrganizationModifier = &v
}

// GetOrganizationLastModified returns the OrganizationLastModified field value if set, zero value otherwise.
func (o *CreateOrganizationCommand) GetOrganizationLastModified() time.Time {
	if o == nil || IsNil(o.OrganizationLastModified) {
		var ret time.Time
		return ret
	}
	return *o.OrganizationLastModified
}

// GetOrganizationLastModifiedOk returns a tuple with the OrganizationLastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetOrganizationLastModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OrganizationLastModified) {
		return nil, false
	}
	return o.OrganizationLastModified, true
}

// HasOrganizationLastModified returns a boolean if a field has been set.
func (o *CreateOrganizationCommand) HasOrganizationLastModified() bool {
	if o != nil && !IsNil(o.OrganizationLastModified) {
		return true
	}

	return false
}

// SetOrganizationLastModified gets a reference to the given time.Time and assigns it to the OrganizationLastModified field.
func (o *CreateOrganizationCommand) SetOrganizationLastModified(v time.Time) {
	o.OrganizationLastModified = &v
}

// GetOrganizationName returns the OrganizationName field value
func (o *CreateOrganizationCommand) GetOrganizationName() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationCommand) GetOrganizationNameOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationName, true
}

// SetOrganizationName sets field value
func (o *CreateOrganizationCommand) SetOrganizationName(v map[string]string) {
	o.OrganizationName = v
}

func (o CreateOrganizationCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	toSerialize["organization/id"] = o.OrganizationId
	toSerialize["organization/short-name"] = o.OrganizationShortName
	if !IsNil(o.OrganizationReviewEmails) {
		toSerialize["organization/review-emails"] = o.OrganizationReviewEmails
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.OrganizationOwners) {
		toSerialize["organization/owners"] = o.OrganizationOwners
	}
	if !IsNil(o.OrganizationModifier) {
		toSerialize["organization/modifier"] = o.OrganizationModifier
	}
	if !IsNil(o.OrganizationLastModified) {
		toSerialize["organization/last-modified"] = o.OrganizationLastModified
	}
	toSerialize["organization/name"] = o.OrganizationName
	return toSerialize, nil
}

func (o *CreateOrganizationCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization/id",
		"organization/short-name",
		"organization/name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrganizationCommand := _CreateOrganizationCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrganizationCommand)

	if err != nil {
		return err
	}

	*o = CreateOrganizationCommand(varCreateOrganizationCommand)

	return err
}

type NullableCreateOrganizationCommand struct {
	value *CreateOrganizationCommand
	isSet bool
}

func (v NullableCreateOrganizationCommand) Get() *CreateOrganizationCommand {
	return v.value
}

func (v *NullableCreateOrganizationCommand) Set(val *CreateOrganizationCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationCommand(val *CreateOrganizationCommand) *NullableCreateOrganizationCommand {
	return &NullableCreateOrganizationCommand{value: val, isSet: true}
}

func (v NullableCreateOrganizationCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
