/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response8050Restrictions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response8050Restrictions{}

// Response8050Restrictions struct for Response8050Restrictions
type Response8050Restrictions struct {
	Type   string                   `json:"type"`
	Values []map[string]interface{} `json:"values,omitempty"`
}

type _Response8050Restrictions Response8050Restrictions

// NewResponse8050Restrictions instantiates a new Response8050Restrictions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse8050Restrictions(type_ string) *Response8050Restrictions {
	this := Response8050Restrictions{}
	this.Type = type_
	return &this
}

// NewResponse8050RestrictionsWithDefaults instantiates a new Response8050Restrictions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse8050RestrictionsWithDefaults() *Response8050Restrictions {
	this := Response8050Restrictions{}
	return &this
}

// GetType returns the Type field value
func (o *Response8050Restrictions) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Response8050Restrictions) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Response8050Restrictions) SetType(v string) {
	o.Type = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *Response8050Restrictions) GetValues() []map[string]interface{} {
	if o == nil || IsNil(o.Values) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response8050Restrictions) GetValuesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *Response8050Restrictions) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []map[string]interface{} and assigns it to the Values field.
func (o *Response8050Restrictions) SetValues(v []map[string]interface{}) {
	o.Values = v
}

func (o Response8050Restrictions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response8050Restrictions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

func (o *Response8050Restrictions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse8050Restrictions := _Response8050Restrictions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse8050Restrictions)

	if err != nil {
		return err
	}

	*o = Response8050Restrictions(varResponse8050Restrictions)

	return err
}

type NullableResponse8050Restrictions struct {
	value *Response8050Restrictions
	isSet bool
}

func (v NullableResponse8050Restrictions) Get() *Response8050Restrictions {
	return v.value
}

func (v *NullableResponse8050Restrictions) Set(val *Response8050Restrictions) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse8050Restrictions) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse8050Restrictions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse8050Restrictions(val *Response8050Restrictions) *NullableResponse8050Restrictions {
	return &NullableResponse8050Restrictions{value: val, isSet: true}
}

func (v NullableResponse8050Restrictions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse8050Restrictions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
