/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RequestDecisionCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestDecisionCommand{}

// RequestDecisionCommand struct for RequestDecisionCommand
type RequestDecisionCommand struct {
	ApplicationId int64               `json:"application-id"`
	Comment       *string             `json:"comment,omitempty"`
	Attachments   []CommandAttachment `json:"attachments,omitempty"`
	Deciders      []string            `json:"deciders"`
}

type _RequestDecisionCommand RequestDecisionCommand

// NewRequestDecisionCommand instantiates a new RequestDecisionCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestDecisionCommand(applicationId int64, deciders []string) *RequestDecisionCommand {
	this := RequestDecisionCommand{}
	this.ApplicationId = applicationId
	this.Deciders = deciders
	return &this
}

// NewRequestDecisionCommandWithDefaults instantiates a new RequestDecisionCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestDecisionCommandWithDefaults() *RequestDecisionCommand {
	this := RequestDecisionCommand{}
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *RequestDecisionCommand) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *RequestDecisionCommand) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *RequestDecisionCommand) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *RequestDecisionCommand) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestDecisionCommand) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *RequestDecisionCommand) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *RequestDecisionCommand) SetComment(v string) {
	o.Comment = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *RequestDecisionCommand) GetAttachments() []CommandAttachment {
	if o == nil || IsNil(o.Attachments) {
		var ret []CommandAttachment
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestDecisionCommand) GetAttachmentsOk() ([]CommandAttachment, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *RequestDecisionCommand) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []CommandAttachment and assigns it to the Attachments field.
func (o *RequestDecisionCommand) SetAttachments(v []CommandAttachment) {
	o.Attachments = v
}

// GetDeciders returns the Deciders field value
func (o *RequestDecisionCommand) GetDeciders() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Deciders
}

// GetDecidersOk returns a tuple with the Deciders field value
// and a boolean to check if the value has been set.
func (o *RequestDecisionCommand) GetDecidersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deciders, true
}

// SetDeciders sets field value
func (o *RequestDecisionCommand) SetDeciders(v []string) {
	o.Deciders = v
}

func (o RequestDecisionCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestDecisionCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["application-id"] = o.ApplicationId
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	toSerialize["deciders"] = o.Deciders
	return toSerialize, nil
}

func (o *RequestDecisionCommand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"application-id",
		"deciders",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestDecisionCommand := _RequestDecisionCommand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestDecisionCommand)

	if err != nil {
		return err
	}

	*o = RequestDecisionCommand(varRequestDecisionCommand)

	return err
}

type NullableRequestDecisionCommand struct {
	value *RequestDecisionCommand
	isSet bool
}

func (v NullableRequestDecisionCommand) Get() *RequestDecisionCommand {
	return v.value
}

func (v *NullableRequestDecisionCommand) Set(val *RequestDecisionCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestDecisionCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestDecisionCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestDecisionCommand(val *RequestDecisionCommand) *NullableRequestDecisionCommand {
	return &NullableRequestDecisionCommand{value: val, isSet: true}
}

func (v NullableRequestDecisionCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestDecisionCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
