/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response7841ResourcesDuoCodesRestrictionsValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response7841ResourcesDuoCodesRestrictionsValues{}

// Response7841ResourcesDuoCodesRestrictionsValues struct for Response7841ResourcesDuoCodesRestrictionsValues
type Response7841ResourcesDuoCodesRestrictionsValues struct {
	Value string `json:"value"`
}

type _Response7841ResourcesDuoCodesRestrictionsValues Response7841ResourcesDuoCodesRestrictionsValues

// NewResponse7841ResourcesDuoCodesRestrictionsValues instantiates a new Response7841ResourcesDuoCodesRestrictionsValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse7841ResourcesDuoCodesRestrictionsValues(value string) *Response7841ResourcesDuoCodesRestrictionsValues {
	this := Response7841ResourcesDuoCodesRestrictionsValues{}
	this.Value = value
	return &this
}

// NewResponse7841ResourcesDuoCodesRestrictionsValuesWithDefaults instantiates a new Response7841ResourcesDuoCodesRestrictionsValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse7841ResourcesDuoCodesRestrictionsValuesWithDefaults() *Response7841ResourcesDuoCodesRestrictionsValues {
	this := Response7841ResourcesDuoCodesRestrictionsValues{}
	return &this
}

// GetValue returns the Value field value
func (o *Response7841ResourcesDuoCodesRestrictionsValues) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Response7841ResourcesDuoCodesRestrictionsValues) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Response7841ResourcesDuoCodesRestrictionsValues) SetValue(v string) {
	o.Value = v
}

func (o Response7841ResourcesDuoCodesRestrictionsValues) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response7841ResourcesDuoCodesRestrictionsValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *Response7841ResourcesDuoCodesRestrictionsValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse7841ResourcesDuoCodesRestrictionsValues := _Response7841ResourcesDuoCodesRestrictionsValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse7841ResourcesDuoCodesRestrictionsValues)

	if err != nil {
		return err
	}

	*o = Response7841ResourcesDuoCodesRestrictionsValues(varResponse7841ResourcesDuoCodesRestrictionsValues)

	return err
}

type NullableResponse7841ResourcesDuoCodesRestrictionsValues struct {
	value *Response7841ResourcesDuoCodesRestrictionsValues
	isSet bool
}

func (v NullableResponse7841ResourcesDuoCodesRestrictionsValues) Get() *Response7841ResourcesDuoCodesRestrictionsValues {
	return v.value
}

func (v *NullableResponse7841ResourcesDuoCodesRestrictionsValues) Set(val *Response7841ResourcesDuoCodesRestrictionsValues) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse7841ResourcesDuoCodesRestrictionsValues) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse7841ResourcesDuoCodesRestrictionsValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse7841ResourcesDuoCodesRestrictionsValues(val *Response7841ResourcesDuoCodesRestrictionsValues) *NullableResponse7841ResourcesDuoCodesRestrictionsValues {
	return &NullableResponse7841ResourcesDuoCodesRestrictionsValues{value: val, isSet: true}
}

func (v NullableResponse7841ResourcesDuoCodesRestrictionsValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse7841ResourcesDuoCodesRestrictionsValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
