/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"encoding/json"
)

// checks if the UpdateUserSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUserSettings{}

// UpdateUserSettings struct for UpdateUserSettings
type UpdateUserSettings struct {
	Language          *string        `json:"language,omitempty"`
	NotificationEmail NullableString `json:"notification-email,omitempty"`
}

// NewUpdateUserSettings instantiates a new UpdateUserSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserSettings() *UpdateUserSettings {
	this := UpdateUserSettings{}
	return &this
}

// NewUpdateUserSettingsWithDefaults instantiates a new UpdateUserSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserSettingsWithDefaults() *UpdateUserSettings {
	this := UpdateUserSettings{}
	return &this
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *UpdateUserSettings) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserSettings) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *UpdateUserSettings) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *UpdateUserSettings) SetLanguage(v string) {
	o.Language = &v
}

// GetNotificationEmail returns the NotificationEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateUserSettings) GetNotificationEmail() string {
	if o == nil || IsNil(o.NotificationEmail.Get()) {
		var ret string
		return ret
	}
	return *o.NotificationEmail.Get()
}

// GetNotificationEmailOk returns a tuple with the NotificationEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateUserSettings) GetNotificationEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NotificationEmail.Get(), o.NotificationEmail.IsSet()
}

// HasNotificationEmail returns a boolean if a field has been set.
func (o *UpdateUserSettings) HasNotificationEmail() bool {
	if o != nil && o.NotificationEmail.IsSet() {
		return true
	}

	return false
}

// SetNotificationEmail gets a reference to the given NullableString and assigns it to the NotificationEmail field.
func (o *UpdateUserSettings) SetNotificationEmail(v string) {
	o.NotificationEmail.Set(&v)
}

// SetNotificationEmailNil sets the value for NotificationEmail to be an explicit nil
func (o *UpdateUserSettings) SetNotificationEmailNil() {
	o.NotificationEmail.Set(nil)
}

// UnsetNotificationEmail ensures that no value is present for NotificationEmail, not even an explicit nil
func (o *UpdateUserSettings) UnsetNotificationEmail() {
	o.NotificationEmail.Unset()
}

func (o UpdateUserSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUserSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if o.NotificationEmail.IsSet() {
		toSerialize["notification-email"] = o.NotificationEmail.Get()
	}
	return toSerialize, nil
}

type NullableUpdateUserSettings struct {
	value *UpdateUserSettings
	isSet bool
}

func (v NullableUpdateUserSettings) Get() *UpdateUserSettings {
	return v.value
}

func (v *NullableUpdateUserSettings) Set(val *UpdateUserSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserSettings(val *UpdateUserSettings) *NullableUpdateUserSettings {
	return &NullableUpdateUserSettings{value: val, isSet: true}
}

func (v NullableUpdateUserSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
