/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateApplicationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationResponse{}

// CreateApplicationResponse struct for CreateApplicationResponse
type CreateApplicationResponse struct {
	Success       bool                     `json:"success"`
	Errors        []map[string]interface{} `json:"errors,omitempty"`
	Warnings      []map[string]interface{} `json:"warnings,omitempty"`
	ApplicationId *int64                   `json:"application-id,omitempty"`
}

type _CreateApplicationResponse CreateApplicationResponse

// NewCreateApplicationResponse instantiates a new CreateApplicationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationResponse(success bool) *CreateApplicationResponse {
	this := CreateApplicationResponse{}
	this.Success = success
	return &this
}

// NewCreateApplicationResponseWithDefaults instantiates a new CreateApplicationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationResponseWithDefaults() *CreateApplicationResponse {
	this := CreateApplicationResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *CreateApplicationResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *CreateApplicationResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CreateApplicationResponse) GetErrors() []map[string]interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationResponse) GetErrorsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CreateApplicationResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []map[string]interface{} and assigns it to the Errors field.
func (o *CreateApplicationResponse) SetErrors(v []map[string]interface{}) {
	o.Errors = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *CreateApplicationResponse) GetWarnings() []map[string]interface{} {
	if o == nil || IsNil(o.Warnings) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationResponse) GetWarningsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *CreateApplicationResponse) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []map[string]interface{} and assigns it to the Warnings field.
func (o *CreateApplicationResponse) SetWarnings(v []map[string]interface{}) {
	o.Warnings = v
}

// GetApplicationId returns the ApplicationId field value if set, zero value otherwise.
func (o *CreateApplicationResponse) GetApplicationId() int64 {
	if o == nil || IsNil(o.ApplicationId) {
		var ret int64
		return ret
	}
	return *o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationResponse) GetApplicationIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ApplicationId) {
		return nil, false
	}
	return o.ApplicationId, true
}

// HasApplicationId returns a boolean if a field has been set.
func (o *CreateApplicationResponse) HasApplicationId() bool {
	if o != nil && !IsNil(o.ApplicationId) {
		return true
	}

	return false
}

// SetApplicationId gets a reference to the given int64 and assigns it to the ApplicationId field.
func (o *CreateApplicationResponse) SetApplicationId(v int64) {
	o.ApplicationId = &v
}

func (o CreateApplicationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	if !IsNil(o.ApplicationId) {
		toSerialize["application-id"] = o.ApplicationId
	}
	return toSerialize, nil
}

func (o *CreateApplicationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateApplicationResponse := _CreateApplicationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateApplicationResponse)

	if err != nil {
		return err
	}

	*o = CreateApplicationResponse(varCreateApplicationResponse)

	return err
}

type NullableCreateApplicationResponse struct {
	value *CreateApplicationResponse
	isSet bool
}

func (v NullableCreateApplicationResponse) Get() *CreateApplicationResponse {
	return v.value
}

func (v *NullableCreateApplicationResponse) Set(val *CreateApplicationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationResponse(val *CreateApplicationResponse) *NullableCreateApplicationResponse {
	return &NullableCreateApplicationResponse{value: val, isSet: true}
}

func (v NullableCreateApplicationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
