/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response6598AttachmentsEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response6598AttachmentsEvent{}

// Response6598AttachmentsEvent struct for Response6598AttachmentsEvent
type Response6598AttachmentsEvent struct {
	EventId int64 `json:"event/id"`
}

type _Response6598AttachmentsEvent Response6598AttachmentsEvent

// NewResponse6598AttachmentsEvent instantiates a new Response6598AttachmentsEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse6598AttachmentsEvent(eventId int64) *Response6598AttachmentsEvent {
	this := Response6598AttachmentsEvent{}
	this.EventId = eventId
	return &this
}

// NewResponse6598AttachmentsEventWithDefaults instantiates a new Response6598AttachmentsEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse6598AttachmentsEventWithDefaults() *Response6598AttachmentsEvent {
	this := Response6598AttachmentsEvent{}
	return &this
}

// GetEventId returns the EventId field value
func (o *Response6598AttachmentsEvent) GetEventId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *Response6598AttachmentsEvent) GetEventIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *Response6598AttachmentsEvent) SetEventId(v int64) {
	o.EventId = v
}

func (o Response6598AttachmentsEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response6598AttachmentsEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event/id"] = o.EventId
	return toSerialize, nil
}

func (o *Response6598AttachmentsEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event/id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse6598AttachmentsEvent := _Response6598AttachmentsEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse6598AttachmentsEvent)

	if err != nil {
		return err
	}

	*o = Response6598AttachmentsEvent(varResponse6598AttachmentsEvent)

	return err
}

type NullableResponse6598AttachmentsEvent struct {
	value *Response6598AttachmentsEvent
	isSet bool
}

func (v NullableResponse6598AttachmentsEvent) Get() *Response6598AttachmentsEvent {
	return v.value
}

func (v *NullableResponse6598AttachmentsEvent) Set(val *Response6598AttachmentsEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse6598AttachmentsEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse6598AttachmentsEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse6598AttachmentsEvent(val *Response6598AttachmentsEvent) *NullableResponse6598AttachmentsEvent {
	return &NullableResponse6598AttachmentsEvent{value: val, isSet: true}
}

func (v NullableResponse6598AttachmentsEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse6598AttachmentsEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
