/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateInvitationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInvitationResponse{}

// CreateInvitationResponse struct for CreateInvitationResponse
type CreateInvitationResponse struct {
	Success      bool                     `json:"success"`
	InvitationId *int64                   `json:"invitation/id,omitempty"`
	Errors       []map[string]interface{} `json:"errors,omitempty"`
}

type _CreateInvitationResponse CreateInvitationResponse

// NewCreateInvitationResponse instantiates a new CreateInvitationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInvitationResponse(success bool) *CreateInvitationResponse {
	this := CreateInvitationResponse{}
	this.Success = success
	return &this
}

// NewCreateInvitationResponseWithDefaults instantiates a new CreateInvitationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInvitationResponseWithDefaults() *CreateInvitationResponse {
	this := CreateInvitationResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *CreateInvitationResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *CreateInvitationResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *CreateInvitationResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetInvitationId returns the InvitationId field value if set, zero value otherwise.
func (o *CreateInvitationResponse) GetInvitationId() int64 {
	if o == nil || IsNil(o.InvitationId) {
		var ret int64
		return ret
	}
	return *o.InvitationId
}

// GetInvitationIdOk returns a tuple with the InvitationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInvitationResponse) GetInvitationIdOk() (*int64, bool) {
	if o == nil || IsNil(o.InvitationId) {
		return nil, false
	}
	return o.InvitationId, true
}

// HasInvitationId returns a boolean if a field has been set.
func (o *CreateInvitationResponse) HasInvitationId() bool {
	if o != nil && !IsNil(o.InvitationId) {
		return true
	}

	return false
}

// SetInvitationId gets a reference to the given int64 and assigns it to the InvitationId field.
func (o *CreateInvitationResponse) SetInvitationId(v int64) {
	o.InvitationId = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CreateInvitationResponse) GetErrors() []map[string]interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInvitationResponse) GetErrorsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CreateInvitationResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []map[string]interface{} and assigns it to the Errors field.
func (o *CreateInvitationResponse) SetErrors(v []map[string]interface{}) {
	o.Errors = v
}

func (o CreateInvitationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInvitationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	if !IsNil(o.InvitationId) {
		toSerialize["invitation/id"] = o.InvitationId
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *CreateInvitationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInvitationResponse := _CreateInvitationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateInvitationResponse)

	if err != nil {
		return err
	}

	*o = CreateInvitationResponse(varCreateInvitationResponse)

	return err
}

type NullableCreateInvitationResponse struct {
	value *CreateInvitationResponse
	isSet bool
}

func (v NullableCreateInvitationResponse) Get() *CreateInvitationResponse {
	return v.value
}

func (v *NullableCreateInvitationResponse) Set(val *CreateInvitationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInvitationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInvitationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInvitationResponse(val *CreateInvitationResponse) *NullableCreateInvitationResponse {
	return &NullableCreateInvitationResponse{value: val, isSet: true}
}

func (v NullableCreateInvitationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInvitationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
