/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationAttachmentsEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationAttachmentsEvent{}

// ApplicationAttachmentsEvent struct for ApplicationAttachmentsEvent
type ApplicationAttachmentsEvent struct {
	EventId int64 `json:"event/id"`
}

type _ApplicationAttachmentsEvent ApplicationAttachmentsEvent

// NewApplicationAttachmentsEvent instantiates a new ApplicationAttachmentsEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationAttachmentsEvent(eventId int64) *ApplicationAttachmentsEvent {
	this := ApplicationAttachmentsEvent{}
	this.EventId = eventId
	return &this
}

// NewApplicationAttachmentsEventWithDefaults instantiates a new ApplicationAttachmentsEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationAttachmentsEventWithDefaults() *ApplicationAttachmentsEvent {
	this := ApplicationAttachmentsEvent{}
	return &this
}

// GetEventId returns the EventId field value
func (o *ApplicationAttachmentsEvent) GetEventId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *ApplicationAttachmentsEvent) GetEventIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *ApplicationAttachmentsEvent) SetEventId(v int64) {
	o.EventId = v
}

func (o ApplicationAttachmentsEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationAttachmentsEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event/id"] = o.EventId
	return toSerialize, nil
}

func (o *ApplicationAttachmentsEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event/id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationAttachmentsEvent := _ApplicationAttachmentsEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationAttachmentsEvent)

	if err != nil {
		return err
	}

	*o = ApplicationAttachmentsEvent(varApplicationAttachmentsEvent)

	return err
}

type NullableApplicationAttachmentsEvent struct {
	value *ApplicationAttachmentsEvent
	isSet bool
}

func (v NullableApplicationAttachmentsEvent) Get() *ApplicationAttachmentsEvent {
	return v.value
}

func (v *NullableApplicationAttachmentsEvent) Set(val *ApplicationAttachmentsEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationAttachmentsEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationAttachmentsEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationAttachmentsEvent(val *ApplicationAttachmentsEvent) *NullableApplicationAttachmentsEvent {
	return &NullableApplicationAttachmentsEvent{value: val, isSet: true}
}

func (v NullableApplicationAttachmentsEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationAttachmentsEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
