/*
REMS API

REMS API Services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package remsclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Response6598ResourcesDuo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Response6598ResourcesDuo{}

// Response6598ResourcesDuo struct for Response6598ResourcesDuo
type Response6598ResourcesDuo struct {
	DuoCodes []DuoCodeFull `json:"duo/codes"`
}

type _Response6598ResourcesDuo Response6598ResourcesDuo

// NewResponse6598ResourcesDuo instantiates a new Response6598ResourcesDuo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse6598ResourcesDuo(duoCodes []DuoCodeFull) *Response6598ResourcesDuo {
	this := Response6598ResourcesDuo{}
	this.DuoCodes = duoCodes
	return &this
}

// NewResponse6598ResourcesDuoWithDefaults instantiates a new Response6598ResourcesDuo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse6598ResourcesDuoWithDefaults() *Response6598ResourcesDuo {
	this := Response6598ResourcesDuo{}
	return &this
}

// GetDuoCodes returns the DuoCodes field value
func (o *Response6598ResourcesDuo) GetDuoCodes() []DuoCodeFull {
	if o == nil {
		var ret []DuoCodeFull
		return ret
	}

	return o.DuoCodes
}

// GetDuoCodesOk returns a tuple with the DuoCodes field value
// and a boolean to check if the value has been set.
func (o *Response6598ResourcesDuo) GetDuoCodesOk() ([]DuoCodeFull, bool) {
	if o == nil {
		return nil, false
	}
	return o.DuoCodes, true
}

// SetDuoCodes sets field value
func (o *Response6598ResourcesDuo) SetDuoCodes(v []DuoCodeFull) {
	o.DuoCodes = v
}

func (o Response6598ResourcesDuo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Response6598ResourcesDuo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duo/codes"] = o.DuoCodes
	return toSerialize, nil
}

func (o *Response6598ResourcesDuo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duo/codes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponse6598ResourcesDuo := _Response6598ResourcesDuo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponse6598ResourcesDuo)

	if err != nil {
		return err
	}

	*o = Response6598ResourcesDuo(varResponse6598ResourcesDuo)

	return err
}

type NullableResponse6598ResourcesDuo struct {
	value *Response6598ResourcesDuo
	isSet bool
}

func (v NullableResponse6598ResourcesDuo) Get() *Response6598ResourcesDuo {
	return v.value
}

func (v *NullableResponse6598ResourcesDuo) Set(val *Response6598ResourcesDuo) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse6598ResourcesDuo) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse6598ResourcesDuo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse6598ResourcesDuo(val *Response6598ResourcesDuo) *NullableResponse6598ResourcesDuo {
	return &NullableResponse6598ResourcesDuo{value: val, isSet: true}
}

func (v NullableResponse6598ResourcesDuo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse6598ResourcesDuo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
